// Package logsadapterclientgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package logsadapterclientgen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlertRuleRequestConditionOperator.
const (
	AlertRuleRequestConditionOperatorEq  AlertRuleRequestConditionOperator = "eq"
	AlertRuleRequestConditionOperatorGt  AlertRuleRequestConditionOperator = "gt"
	AlertRuleRequestConditionOperatorGte AlertRuleRequestConditionOperator = "gte"
	AlertRuleRequestConditionOperatorLt  AlertRuleRequestConditionOperator = "lt"
	AlertRuleRequestConditionOperatorLte AlertRuleRequestConditionOperator = "lte"
	AlertRuleRequestConditionOperatorNeq AlertRuleRequestConditionOperator = "neq"
)

// Defines values for AlertRuleResponseConditionOperator.
const (
	AlertRuleResponseConditionOperatorEq  AlertRuleResponseConditionOperator = "eq"
	AlertRuleResponseConditionOperatorGt  AlertRuleResponseConditionOperator = "gt"
	AlertRuleResponseConditionOperatorGte AlertRuleResponseConditionOperator = "gte"
	AlertRuleResponseConditionOperatorLt  AlertRuleResponseConditionOperator = "lt"
	AlertRuleResponseConditionOperatorLte AlertRuleResponseConditionOperator = "lte"
	AlertRuleResponseConditionOperatorNeq AlertRuleResponseConditionOperator = "neq"
)

// Defines values for AlertRuleResponseSourceMetric.
const (
	CpuUsage    AlertRuleResponseSourceMetric = "cpu_usage"
	MemoryUsage AlertRuleResponseSourceMetric = "memory_usage"
)

// Defines values for AlertWebhookResponseStatus.
const (
	Error   AlertWebhookResponseStatus = "error"
	Success AlertWebhookResponseStatus = "success"
)

// Defines values for AlertingRuleSyncResponseAction.
const (
	Created   AlertingRuleSyncResponseAction = "created"
	Deleted   AlertingRuleSyncResponseAction = "deleted"
	Unchanged AlertingRuleSyncResponseAction = "unchanged"
	Updated   AlertingRuleSyncResponseAction = "updated"
)

// Defines values for AlertingRuleSyncResponseStatus.
const (
	Failed AlertingRuleSyncResponseStatus = "failed"
	Synced AlertingRuleSyncResponseStatus = "synced"
)

// Defines values for ErrorResponseTitle.
const (
	BadRequest          ErrorResponseTitle = "badRequest"
	Conflict            ErrorResponseTitle = "conflict"
	Forbidden           ErrorResponseTitle = "forbidden"
	InternalServerError ErrorResponseTitle = "internalServerError"
	NotFound            ErrorResponseTitle = "notFound"
	NotImplemented      ErrorResponseTitle = "notImplemented"
	Unauthorized        ErrorResponseTitle = "unauthorized"
)

// Defines values for EventsQueryRequestSortOrder.
const (
	EventsQueryRequestSortOrderAsc  EventsQueryRequestSortOrder = "asc"
	EventsQueryRequestSortOrderDesc EventsQueryRequestSortOrder = "desc"
)

// Defines values for LogsQueryRequestLogLevels.
const (
	DEBUG LogsQueryRequestLogLevels = "DEBUG"
	ERROR LogsQueryRequestLogLevels = "ERROR"
	INFO  LogsQueryRequestLogLevels = "INFO"
	WARN  LogsQueryRequestLogLevels = "WARN"
)

// Defines values for LogsQueryRequestSortOrder.
const (
	LogsQueryRequestSortOrderAsc  LogsQueryRequestSortOrder = "asc"
	LogsQueryRequestSortOrderDesc LogsQueryRequestSortOrder = "desc"
)

// AlertRuleRequest defines model for AlertRuleRequest.
type AlertRuleRequest struct {
	Condition struct {
		// Enabled Whether the alert rule is enabled
		Enabled bool `json:"enabled"`

		// Interval The interval of time to query for the alert rule
		Interval string `json:"interval"`

		// Operator The operator to use for the alert rule
		Operator AlertRuleRequestConditionOperator `json:"operator"`

		// Threshold The threshold value to use for the alert rule
		Threshold float32 `json:"threshold"`

		// Window The window of time to query for the alert rule
		Window string `json:"window"`
	} `json:"condition"`
	Metadata struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid openapi_types.UUID `json:"componentUid"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid openapi_types.UUID `json:"environmentUid"`

		// Name The name of the alert rule
		Name string `json:"name"`

		// Namespace The namespace of the alert rule CR
		Namespace string `json:"namespace"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid openapi_types.UUID `json:"projectUid"`
	} `json:"metadata"`
	Source struct {
		// Query The query to execute for log based alerts
		Query string `json:"query"`
	} `json:"source"`
}

// AlertRuleRequestConditionOperator The operator to use for the alert rule
type AlertRuleRequestConditionOperator string

// AlertRuleResponse defines model for AlertRuleResponse.
type AlertRuleResponse struct {
	Condition *struct {
		// Enabled Whether the alert rule is enabled
		Enabled *bool `json:"enabled,omitempty"`

		// Interval The interval of time to query for the alert rule
		Interval *string `json:"interval,omitempty"`

		// Operator The operator to use for the alert rule
		Operator *AlertRuleResponseConditionOperator `json:"operator,omitempty"`

		// Threshold The threshold value to use for the alert rule
		Threshold *float32 `json:"threshold,omitempty"`

		// Window The window of time to query for the alert rule
		Window *string `json:"window,omitempty"`
	} `json:"condition,omitempty"`
	Metadata *struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid *openapi_types.UUID `json:"componentUid,omitempty"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid *openapi_types.UUID `json:"environmentUid,omitempty"`

		// Name The name of the alert rule
		Name *string `json:"name,omitempty"`

		// Namespace The namespace of the alert rule CR
		Namespace *string `json:"namespace,omitempty"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid *openapi_types.UUID `json:"projectUid,omitempty"`
	} `json:"metadata,omitempty"`
	Source *struct {
		// Metric The metric to query for metric based alerts
		Metric *AlertRuleResponseSourceMetric `json:"metric,omitempty"`

		// Query The query to execute for log based alerts
		Query *string `json:"query,omitempty"`
	} `json:"source,omitempty"`
}

// AlertRuleResponseConditionOperator The operator to use for the alert rule
type AlertRuleResponseConditionOperator string

// AlertRuleResponseSourceMetric The metric to query for metric based alerts
type AlertRuleResponseSourceMetric string

// AlertWebhookResponse defines model for AlertWebhookResponse.
type AlertWebhookResponse struct {
	// Message The message of the alert webhook
	Message *string `json:"message,omitempty"`

	// Status The status of the alert webhook
	Status *AlertWebhookResponseStatus `json:"status,omitempty"`
}

// AlertWebhookResponseStatus The status of the alert webhook
type AlertWebhookResponseStatus string

// AlertingRuleSyncResponse defines model for AlertingRuleSyncResponse.
type AlertingRuleSyncResponse struct {
	// Action The action taken on the alert rule
	Action *AlertingRuleSyncResponseAction `json:"action,omitempty"`

	// LastSyncedAt The timestamp of the last sync
	LastSyncedAt *string `json:"lastSyncedAt,omitempty"`

	// RuleBackendId The backend ID (UID from observability backend) of the alert rule
	RuleBackendId *string `json:"ruleBackendId,omitempty"`

	// RuleLogicalId The logical ID (name) of the alert rule
	RuleLogicalId *string `json:"ruleLogicalId,omitempty"`

	// Status The status of the alert rule
	Status *AlertingRuleSyncResponseStatus `json:"status,omitempty"`
}

// AlertingRuleSyncResponseAction The action taken on the alert rule
type AlertingRuleSyncResponseAction string

// AlertingRuleSyncResponseStatus The status of the alert rule
type AlertingRuleSyncResponseStatus string

// ComponentLogEntry defines model for ComponentLogEntry.
type ComponentLogEntry struct {
	// Level The log level
	Level *string `json:"level,omitempty"`

	// Log The log message
	Log *string `json:"log,omitempty"`

	// Metadata The metadata of the log entry
	Metadata *struct {
		// ComponentName The OpenChoreo component name that generated the log
		ComponentName *string `json:"componentName,omitempty"`

		// ComponentUid The OpenChoreo component UID that generated the log
		ComponentUid *openapi_types.UUID `json:"componentUid,omitempty"`

		// ContainerName The container name that generated the log
		ContainerName *string `json:"containerName,omitempty"`

		// EnvironmentName The OpenChoreo environment name that generated the log
		EnvironmentName *string `json:"environmentName,omitempty"`

		// EnvironmentUid The OpenChoreo environment UID that generated the log
		EnvironmentUid *openapi_types.UUID `json:"environmentUid,omitempty"`

		// NamespaceName The OpenChoreo namespace name that generated the log
		NamespaceName *string `json:"namespaceName,omitempty"`

		// PodName The Kubernetes pod name that generated the log
		PodName *string `json:"podName,omitempty"`

		// PodNamespace The namespace of the Kubernetes pod that generated the log
		PodNamespace *string `json:"podNamespace,omitempty"`

		// ProjectName The OpenChoreo project name that generated the log
		ProjectName *string `json:"projectName,omitempty"`

		// ProjectUid The OpenChoreo project UID that generated the log
		ProjectUid *openapi_types.UUID `json:"projectUid,omitempty"`
	} `json:"metadata,omitempty"`

	// Timestamp The timestamp of the log entry
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ComponentSearchScope defines model for ComponentSearchScope.
type ComponentSearchScope struct {
	ComponentUid   *string `json:"componentUid,omitempty"`
	EnvironmentUid *string `json:"environmentUid,omitempty"`
	Namespace      string  `json:"namespace"`
	ProjectUid     *string `json:"projectUid,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// ErrorCode The error code from observer service
	ErrorCode *string `json:"errorCode,omitempty"`

	// Message Human-readable error message
	Message *string `json:"message,omitempty"`

	// Title The error message
	Title *ErrorResponseTitle `json:"title,omitempty"`
}

// ErrorResponseTitle The error message
type ErrorResponseTitle string

// EventEntry defines model for EventEntry.
type EventEntry struct {
	// Message The event message
	Message *string `json:"message,omitempty"`

	// Metadata The metadata of the event
	Metadata *struct {
		// ComponentName The OpenChoreo component name the event is associated with
		ComponentName *string `json:"componentName,omitempty"`

		// ComponentUid The OpenChoreo component UID the event is associated with
		ComponentUid *openapi_types.UUID `json:"componentUid,omitempty"`

		// EnvironmentName The OpenChoreo environment name the event is associated with
		EnvironmentName *string `json:"environmentName,omitempty"`

		// EnvironmentUid The OpenChoreo environment UID the event is associated with
		EnvironmentUid *openapi_types.UUID `json:"environmentUid,omitempty"`

		// NamespaceName The OpenChoreo namespace name the event is associated with
		NamespaceName *string `json:"namespaceName,omitempty"`

		// ObjectKind The kind of the Kubernetes object the event involves (e.g. CronJob)
		ObjectKind *string `json:"objectKind,omitempty"`

		// ObjectName The name of the Kubernetes object the event involves
		ObjectName *string `json:"objectName,omitempty"`

		// ObjectNamespace The namespace of the Kubernetes object the event involves
		ObjectNamespace *string `json:"objectNamespace,omitempty"`

		// ProjectName The OpenChoreo project name the event is associated with
		ProjectName *string `json:"projectName,omitempty"`

		// ProjectUid The OpenChoreo project UID the event is associated with
		ProjectUid *openapi_types.UUID `json:"projectUid,omitempty"`
	} `json:"metadata,omitempty"`

	// Reason The short, machine-readable reason for the event (e.g. SawCompletedJob)
	Reason *string `json:"reason,omitempty"`

	// Timestamp The timestamp of the event
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Type The event type (e.g. Normal, Warning)
	Type *string `json:"type,omitempty"`
}

// EventsQueryRequest defines model for EventsQueryRequest.
type EventsQueryRequest struct {
	// EndTime The end time of the query
	EndTime time.Time `json:"endTime"`

	// Limit The maximum number of items to return
	Limit       *int                           `json:"limit,omitempty"`
	SearchScope EventsQueryRequest_SearchScope `json:"searchScope"`

	// SortOrder The sort order of the query
	SortOrder *EventsQueryRequestSortOrder `json:"sortOrder,omitempty"`

	// StartTime The start time of the query
	StartTime time.Time `json:"startTime"`
}

// EventsQueryRequest_SearchScope defines model for EventsQueryRequest.SearchScope.
type EventsQueryRequest_SearchScope struct {
	union json.RawMessage
}

// EventsQueryRequestSortOrder The sort order of the query
type EventsQueryRequestSortOrder string

// EventsQueryResponse defines model for EventsQueryResponse.
type EventsQueryResponse struct {
	// Events The events queried successfully
	Events *[]EventEntry `json:"events,omitempty"`

	// TookMs The time taken to query the events in milliseconds
	TookMs *int `json:"tookMs,omitempty"`

	// Total The total number of matching events, capped at 1000
	Total *int `json:"total,omitempty"`
}

// LogsQueryRequest defines model for LogsQueryRequest.
type LogsQueryRequest struct {
	// EndTime The end time of the query
	EndTime time.Time `json:"endTime"`

	// Limit The maximum number of items to return
	Limit        *int                         `json:"limit,omitempty"`
	LogLevels    *[]LogsQueryRequestLogLevels `json:"logLevels,omitempty"`
	SearchPhrase *string                      `json:"searchPhrase,omitempty"`
	SearchScope  LogsQueryRequest_SearchScope `json:"searchScope"`

	// SortOrder The sort order of the query
	SortOrder *LogsQueryRequestSortOrder `json:"sortOrder,omitempty"`

	// StartTime The start time of the query
	StartTime time.Time `json:"startTime"`
}

// LogsQueryRequestLogLevels defines model for LogsQueryRequest.LogLevels.
type LogsQueryRequestLogLevels string

// LogsQueryRequest_SearchScope defines model for LogsQueryRequest.SearchScope.
type LogsQueryRequest_SearchScope struct {
	union json.RawMessage
}

// LogsQueryRequestSortOrder The sort order of the query
type LogsQueryRequestSortOrder string

// LogsQueryResponse defines model for LogsQueryResponse.
type LogsQueryResponse struct {
	// Logs The logs queried successfully
	Logs *LogsQueryResponse_Logs `json:"logs,omitempty"`

	// TookMs The time taken to query the logs in milliseconds
	TookMs *int `json:"tookMs,omitempty"`

	// Total The total number of matching log entries, capped at 1000
	Total *int `json:"total,omitempty"`
}

// LogsQueryResponseLogs0 defines model for .
type LogsQueryResponseLogs0 = []ComponentLogEntry

// LogsQueryResponseLogs1 defines model for .
type LogsQueryResponseLogs1 = []WorkflowLogEntry

// LogsQueryResponse_Logs The logs queried successfully
type LogsQueryResponse_Logs struct {
	union json.RawMessage
}

// WorkflowLogEntry defines model for WorkflowLogEntry.
type WorkflowLogEntry struct {
	// Log The log message
	Log *string `json:"log,omitempty"`

	// Timestamp The timestamp of the log entry
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// WorkflowSearchScope defines model for WorkflowSearchScope.
type WorkflowSearchScope struct {
	Namespace string `json:"namespace"`

	// TaskName Filter events to a specific workflow task
	TaskName        *string `json:"taskName,omitempty"`
	WorkflowRunName *string `json:"workflowRunName,omitempty"`
}

// HandleAlertWebhookJSONBody defines parameters for HandleAlertWebhook.
type HandleAlertWebhookJSONBody = map[string]interface{}

// QueryEventsJSONRequestBody defines body for QueryEvents for application/json ContentType.
type QueryEventsJSONRequestBody = EventsQueryRequest

// QueryLogsJSONRequestBody defines body for QueryLogs for application/json ContentType.
type QueryLogsJSONRequestBody = LogsQueryRequest

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = AlertRuleRequest

// UpdateAlertRuleJSONRequestBody defines body for UpdateAlertRule for application/json ContentType.
type UpdateAlertRuleJSONRequestBody = AlertRuleRequest

// HandleAlertWebhookJSONRequestBody defines body for HandleAlertWebhook for application/json ContentType.
type HandleAlertWebhookJSONRequestBody = HandleAlertWebhookJSONBody

// AsComponentSearchScope returns the union data inside the EventsQueryRequest_SearchScope as a ComponentSearchScope
func (t EventsQueryRequest_SearchScope) AsComponentSearchScope() (ComponentSearchScope, error) {
	var body ComponentSearchScope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComponentSearchScope overwrites any union data inside the EventsQueryRequest_SearchScope as the provided ComponentSearchScope
func (t *EventsQueryRequest_SearchScope) FromComponentSearchScope(v ComponentSearchScope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComponentSearchScope performs a merge with any union data inside the EventsQueryRequest_SearchScope, using the provided ComponentSearchScope
func (t *EventsQueryRequest_SearchScope) MergeComponentSearchScope(v ComponentSearchScope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkflowSearchScope returns the union data inside the EventsQueryRequest_SearchScope as a WorkflowSearchScope
func (t EventsQueryRequest_SearchScope) AsWorkflowSearchScope() (WorkflowSearchScope, error) {
	var body WorkflowSearchScope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkflowSearchScope overwrites any union data inside the EventsQueryRequest_SearchScope as the provided WorkflowSearchScope
func (t *EventsQueryRequest_SearchScope) FromWorkflowSearchScope(v WorkflowSearchScope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkflowSearchScope performs a merge with any union data inside the EventsQueryRequest_SearchScope, using the provided WorkflowSearchScope
func (t *EventsQueryRequest_SearchScope) MergeWorkflowSearchScope(v WorkflowSearchScope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventsQueryRequest_SearchScope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventsQueryRequest_SearchScope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsComponentSearchScope returns the union data inside the LogsQueryRequest_SearchScope as a ComponentSearchScope
func (t LogsQueryRequest_SearchScope) AsComponentSearchScope() (ComponentSearchScope, error) {
	var body ComponentSearchScope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromComponentSearchScope overwrites any union data inside the LogsQueryRequest_SearchScope as the provided ComponentSearchScope
func (t *LogsQueryRequest_SearchScope) FromComponentSearchScope(v ComponentSearchScope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeComponentSearchScope performs a merge with any union data inside the LogsQueryRequest_SearchScope, using the provided ComponentSearchScope
func (t *LogsQueryRequest_SearchScope) MergeComponentSearchScope(v ComponentSearchScope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkflowSearchScope returns the union data inside the LogsQueryRequest_SearchScope as a WorkflowSearchScope
func (t LogsQueryRequest_SearchScope) AsWorkflowSearchScope() (WorkflowSearchScope, error) {
	var body WorkflowSearchScope
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkflowSearchScope overwrites any union data inside the LogsQueryRequest_SearchScope as the provided WorkflowSearchScope
func (t *LogsQueryRequest_SearchScope) FromWorkflowSearchScope(v WorkflowSearchScope) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkflowSearchScope performs a merge with any union data inside the LogsQueryRequest_SearchScope, using the provided WorkflowSearchScope
func (t *LogsQueryRequest_SearchScope) MergeWorkflowSearchScope(v WorkflowSearchScope) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LogsQueryRequest_SearchScope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LogsQueryRequest_SearchScope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsLogsQueryResponseLogs0 returns the union data inside the LogsQueryResponse_Logs as a LogsQueryResponseLogs0
func (t LogsQueryResponse_Logs) AsLogsQueryResponseLogs0() (LogsQueryResponseLogs0, error) {
	var body LogsQueryResponseLogs0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLogsQueryResponseLogs0 overwrites any union data inside the LogsQueryResponse_Logs as the provided LogsQueryResponseLogs0
func (t *LogsQueryResponse_Logs) FromLogsQueryResponseLogs0(v LogsQueryResponseLogs0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLogsQueryResponseLogs0 performs a merge with any union data inside the LogsQueryResponse_Logs, using the provided LogsQueryResponseLogs0
func (t *LogsQueryResponse_Logs) MergeLogsQueryResponseLogs0(v LogsQueryResponseLogs0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLogsQueryResponseLogs1 returns the union data inside the LogsQueryResponse_Logs as a LogsQueryResponseLogs1
func (t LogsQueryResponse_Logs) AsLogsQueryResponseLogs1() (LogsQueryResponseLogs1, error) {
	var body LogsQueryResponseLogs1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLogsQueryResponseLogs1 overwrites any union data inside the LogsQueryResponse_Logs as the provided LogsQueryResponseLogs1
func (t *LogsQueryResponse_Logs) FromLogsQueryResponseLogs1(v LogsQueryResponseLogs1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLogsQueryResponseLogs1 performs a merge with any union data inside the LogsQueryResponse_Logs, using the provided LogsQueryResponseLogs1
func (t *LogsQueryResponse_Logs) MergeLogsQueryResponseLogs1(v LogsQueryResponseLogs1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LogsQueryResponse_Logs) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LogsQueryResponse_Logs) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// QueryEventsWithBody request with any body
	QueryEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	QueryEvents(ctx context.Context, body QueryEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryLogsWithBody request with any body
	QueryLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	QueryLogs(ctx context.Context, body QueryLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAlertRuleWithBody request with any body
	CreateAlertRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAlertRule(ctx context.Context, body CreateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAlertRule request
	DeleteAlertRule(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAlertRule request
	GetAlertRule(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAlertRuleWithBody request with any body
	UpdateAlertRuleWithBody(ctx context.Context, ruleName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateAlertRule(ctx context.Context, ruleName string, body UpdateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HandleAlertWebhookWithBody request with any body
	HandleAlertWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HandleAlertWebhook(ctx context.Context, body HandleAlertWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Health request
	Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) QueryEventsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryEventsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryEvents(ctx context.Context, body QueryEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryEventsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryLogsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryLogs(ctx context.Context, body QueryLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryLogsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAlertRuleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAlertRuleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAlertRule(ctx context.Context, body CreateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAlertRuleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAlertRule(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAlertRuleRequest(c.Server, ruleName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAlertRule(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAlertRuleRequest(c.Server, ruleName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAlertRuleWithBody(ctx context.Context, ruleName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAlertRuleRequestWithBody(c.Server, ruleName, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAlertRule(ctx context.Context, ruleName string, body UpdateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAlertRuleRequest(c.Server, ruleName, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HandleAlertWebhookWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleAlertWebhookRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HandleAlertWebhook(ctx context.Context, body HandleAlertWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleAlertWebhookRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Health(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewQueryEventsRequest calls the generic QueryEvents builder with application/json body
func NewQueryEventsRequest(server string, body QueryEventsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryEventsRequestWithBody(server, "application/json", bodyReader)
}

// NewQueryEventsRequestWithBody generates requests for QueryEvents with any type of body
func NewQueryEventsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/events/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewQueryLogsRequest calls the generic QueryLogs builder with application/json body
func NewQueryLogsRequest(server string, body QueryLogsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewQueryLogsRequestWithBody(server, "application/json", bodyReader)
}

// NewQueryLogsRequestWithBody generates requests for QueryLogs with any type of body
func NewQueryLogsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/logs/query")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateAlertRuleRequest calls the generic CreateAlertRule builder with application/json body
func NewCreateAlertRuleRequest(server string, body CreateAlertRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAlertRuleRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAlertRuleRequestWithBody generates requests for CreateAlertRule with any type of body
func NewCreateAlertRuleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/alerts/rules")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAlertRuleRequest generates requests for DeleteAlertRule
func NewDeleteAlertRuleRequest(server string, ruleName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "ruleName", runtime.ParamLocationPath, ruleName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/alerts/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAlertRuleRequest generates requests for GetAlertRule
func NewGetAlertRuleRequest(server string, ruleName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "ruleName", runtime.ParamLocationPath, ruleName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/alerts/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateAlertRuleRequest calls the generic UpdateAlertRule builder with application/json body
func NewUpdateAlertRuleRequest(server string, ruleName string, body UpdateAlertRuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateAlertRuleRequestWithBody(server, ruleName, "application/json", bodyReader)
}

// NewUpdateAlertRuleRequestWithBody generates requests for UpdateAlertRule with any type of body
func NewUpdateAlertRuleRequestWithBody(server string, ruleName string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "ruleName", runtime.ParamLocationPath, ruleName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/alerts/rules/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHandleAlertWebhookRequest calls the generic HandleAlertWebhook builder with application/json body
func NewHandleAlertWebhookRequest(server string, body HandleAlertWebhookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHandleAlertWebhookRequestWithBody(server, "application/json", bodyReader)
}

// NewHandleAlertWebhookRequestWithBody generates requests for HandleAlertWebhook with any type of body
func NewHandleAlertWebhookRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/alerts/webhook")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthRequest generates requests for Health
func NewHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// QueryEventsWithBodyWithResponse request with any body
	QueryEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryEventsResp, error)

	QueryEventsWithResponse(ctx context.Context, body QueryEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryEventsResp, error)

	// QueryLogsWithBodyWithResponse request with any body
	QueryLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryLogsResp, error)

	QueryLogsWithResponse(ctx context.Context, body QueryLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryLogsResp, error)

	// CreateAlertRuleWithBodyWithResponse request with any body
	CreateAlertRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAlertRuleResp, error)

	CreateAlertRuleWithResponse(ctx context.Context, body CreateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAlertRuleResp, error)

	// DeleteAlertRuleWithResponse request
	DeleteAlertRuleWithResponse(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*DeleteAlertRuleResp, error)

	// GetAlertRuleWithResponse request
	GetAlertRuleWithResponse(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*GetAlertRuleResp, error)

	// UpdateAlertRuleWithBodyWithResponse request with any body
	UpdateAlertRuleWithBodyWithResponse(ctx context.Context, ruleName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAlertRuleResp, error)

	UpdateAlertRuleWithResponse(ctx context.Context, ruleName string, body UpdateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAlertRuleResp, error)

	// HandleAlertWebhookWithBodyWithResponse request with any body
	HandleAlertWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleAlertWebhookResp, error)

	HandleAlertWebhookWithResponse(ctx context.Context, body HandleAlertWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleAlertWebhookResp, error)

	// HealthWithResponse request
	HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResp, error)
}

type QueryEventsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EventsQueryResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON500      *ErrorResponse
	JSON501      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r QueryEventsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryEventsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryLogsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LogsQueryResponse
	JSON400      *ErrorResponse
	JSON401      *ErrorResponse
	JSON403      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r QueryLogsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryLogsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAlertRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AlertingRuleSyncResponse
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateAlertRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAlertRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAlertRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertingRuleSyncResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAlertRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAlertRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAlertRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertRuleResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetAlertRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAlertRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateAlertRuleResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertingRuleSyncResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateAlertRuleResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateAlertRuleResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HandleAlertWebhookResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AlertWebhookResponse
	JSON400      *ErrorResponse
	JSON500      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r HandleAlertWebhookResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HandleAlertWebhookResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status *string `json:"status,omitempty"`
	}
	JSON503 *struct {
		Error  *string `json:"error,omitempty"`
		Status *string `json:"status,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r HealthResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// QueryEventsWithBodyWithResponse request with arbitrary body returning *QueryEventsResp
func (c *ClientWithResponses) QueryEventsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryEventsResp, error) {
	rsp, err := c.QueryEventsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryEventsResp(rsp)
}

func (c *ClientWithResponses) QueryEventsWithResponse(ctx context.Context, body QueryEventsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryEventsResp, error) {
	rsp, err := c.QueryEvents(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryEventsResp(rsp)
}

// QueryLogsWithBodyWithResponse request with arbitrary body returning *QueryLogsResp
func (c *ClientWithResponses) QueryLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*QueryLogsResp, error) {
	rsp, err := c.QueryLogsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryLogsResp(rsp)
}

func (c *ClientWithResponses) QueryLogsWithResponse(ctx context.Context, body QueryLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*QueryLogsResp, error) {
	rsp, err := c.QueryLogs(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryLogsResp(rsp)
}

// CreateAlertRuleWithBodyWithResponse request with arbitrary body returning *CreateAlertRuleResp
func (c *ClientWithResponses) CreateAlertRuleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAlertRuleResp, error) {
	rsp, err := c.CreateAlertRuleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAlertRuleResp(rsp)
}

func (c *ClientWithResponses) CreateAlertRuleWithResponse(ctx context.Context, body CreateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAlertRuleResp, error) {
	rsp, err := c.CreateAlertRule(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAlertRuleResp(rsp)
}

// DeleteAlertRuleWithResponse request returning *DeleteAlertRuleResp
func (c *ClientWithResponses) DeleteAlertRuleWithResponse(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*DeleteAlertRuleResp, error) {
	rsp, err := c.DeleteAlertRule(ctx, ruleName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAlertRuleResp(rsp)
}

// GetAlertRuleWithResponse request returning *GetAlertRuleResp
func (c *ClientWithResponses) GetAlertRuleWithResponse(ctx context.Context, ruleName string, reqEditors ...RequestEditorFn) (*GetAlertRuleResp, error) {
	rsp, err := c.GetAlertRule(ctx, ruleName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAlertRuleResp(rsp)
}

// UpdateAlertRuleWithBodyWithResponse request with arbitrary body returning *UpdateAlertRuleResp
func (c *ClientWithResponses) UpdateAlertRuleWithBodyWithResponse(ctx context.Context, ruleName string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAlertRuleResp, error) {
	rsp, err := c.UpdateAlertRuleWithBody(ctx, ruleName, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAlertRuleResp(rsp)
}

func (c *ClientWithResponses) UpdateAlertRuleWithResponse(ctx context.Context, ruleName string, body UpdateAlertRuleJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAlertRuleResp, error) {
	rsp, err := c.UpdateAlertRule(ctx, ruleName, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAlertRuleResp(rsp)
}

// HandleAlertWebhookWithBodyWithResponse request with arbitrary body returning *HandleAlertWebhookResp
func (c *ClientWithResponses) HandleAlertWebhookWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleAlertWebhookResp, error) {
	rsp, err := c.HandleAlertWebhookWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleAlertWebhookResp(rsp)
}

func (c *ClientWithResponses) HandleAlertWebhookWithResponse(ctx context.Context, body HandleAlertWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleAlertWebhookResp, error) {
	rsp, err := c.HandleAlertWebhook(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleAlertWebhookResp(rsp)
}

// HealthWithResponse request returning *HealthResp
func (c *ClientWithResponses) HealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthResp, error) {
	rsp, err := c.Health(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthResp(rsp)
}

// ParseQueryEventsResp parses an HTTP response from a QueryEventsWithResponse call
func ParseQueryEventsResp(rsp *http.Response) (*QueryEventsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryEventsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EventsQueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 501:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON501 = &dest

	}

	return response, nil
}

// ParseQueryLogsResp parses an HTTP response from a QueryLogsWithResponse call
func ParseQueryLogsResp(rsp *http.Response) (*QueryLogsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryLogsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LogsQueryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateAlertRuleResp parses an HTTP response from a CreateAlertRuleWithResponse call
func ParseCreateAlertRuleResp(rsp *http.Response) (*CreateAlertRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAlertRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AlertingRuleSyncResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteAlertRuleResp parses an HTTP response from a DeleteAlertRuleWithResponse call
func ParseDeleteAlertRuleResp(rsp *http.Response) (*DeleteAlertRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAlertRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertingRuleSyncResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetAlertRuleResp parses an HTTP response from a GetAlertRuleWithResponse call
func ParseGetAlertRuleResp(rsp *http.Response) (*GetAlertRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAlertRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertRuleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateAlertRuleResp parses an HTTP response from a UpdateAlertRuleWithResponse call
func ParseUpdateAlertRuleResp(rsp *http.Response) (*UpdateAlertRuleResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateAlertRuleResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertingRuleSyncResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseHandleAlertWebhookResp parses an HTTP response from a HandleAlertWebhookWithResponse call
func ParseHandleAlertWebhookResp(rsp *http.Response) (*HandleAlertWebhookResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HandleAlertWebhookResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AlertWebhookResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseHealthResp parses an HTTP response from a HealthWithResponse call
func ParseHealthResp(rsp *http.Response) (*HealthResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status *string `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest struct {
			Error  *string `json:"error,omitempty"`
			Status *string `json:"status,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}
