// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateProjectReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) CreateProjectReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectReleaseBinding")
	}

	var r0 *v1alpha1.ProjectReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) *v1alpha1.ProjectReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateProjectReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectReleaseBinding'
type MockService_CreateProjectReleaseBinding_Call struct {
	*mock.Call
}

// CreateProjectReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ProjectReleaseBinding
func (_e *MockService_Expecter) CreateProjectReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_CreateProjectReleaseBinding_Call {
	return &MockService_CreateProjectReleaseBinding_Call{Call: _e.mock.On("CreateProjectReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_CreateProjectReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ProjectReleaseBinding)) *MockService_CreateProjectReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ProjectReleaseBinding))
	})
	return _c
}

func (_c *MockService_CreateProjectReleaseBinding_Call) Return(_a0 *v1alpha1.ProjectReleaseBinding, _a1 error) *MockService_CreateProjectReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateProjectReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error)) *MockService_CreateProjectReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectReleaseBinding provides a mock function with given fields: ctx, namespaceName, projectReleaseBindingName
func (_m *MockService) DeleteProjectReleaseBinding(ctx context.Context, namespaceName string, projectReleaseBindingName string) error {
	ret := _m.Called(ctx, namespaceName, projectReleaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectReleaseBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, projectReleaseBindingName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteProjectReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectReleaseBinding'
type MockService_DeleteProjectReleaseBinding_Call struct {
	*mock.Call
}

// DeleteProjectReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectReleaseBindingName string
func (_e *MockService_Expecter) DeleteProjectReleaseBinding(ctx interface{}, namespaceName interface{}, projectReleaseBindingName interface{}) *MockService_DeleteProjectReleaseBinding_Call {
	return &MockService_DeleteProjectReleaseBinding_Call{Call: _e.mock.On("DeleteProjectReleaseBinding", ctx, namespaceName, projectReleaseBindingName)}
}

func (_c *MockService_DeleteProjectReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, projectReleaseBindingName string)) *MockService_DeleteProjectReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteProjectReleaseBinding_Call) Return(_a0 error) *MockService_DeleteProjectReleaseBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteProjectReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteProjectReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectReleaseBinding provides a mock function with given fields: ctx, namespaceName, projectReleaseBindingName
func (_m *MockService) GetProjectReleaseBinding(ctx context.Context, namespaceName string, projectReleaseBindingName string) (*v1alpha1.ProjectReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, projectReleaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectReleaseBinding")
	}

	var r0 *v1alpha1.ProjectReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ProjectReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, projectReleaseBindingName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ProjectReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, projectReleaseBindingName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, projectReleaseBindingName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProjectReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectReleaseBinding'
type MockService_GetProjectReleaseBinding_Call struct {
	*mock.Call
}

// GetProjectReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectReleaseBindingName string
func (_e *MockService_Expecter) GetProjectReleaseBinding(ctx interface{}, namespaceName interface{}, projectReleaseBindingName interface{}) *MockService_GetProjectReleaseBinding_Call {
	return &MockService_GetProjectReleaseBinding_Call{Call: _e.mock.On("GetProjectReleaseBinding", ctx, namespaceName, projectReleaseBindingName)}
}

func (_c *MockService_GetProjectReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, projectReleaseBindingName string)) *MockService_GetProjectReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetProjectReleaseBinding_Call) Return(_a0 *v1alpha1.ProjectReleaseBinding, _a1 error) *MockService_GetProjectReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProjectReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ProjectReleaseBinding, error)) *MockService_GetProjectReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectReleaseBindings provides a mock function with given fields: ctx, namespaceName, projectName, opts
func (_m *MockService) ListProjectReleaseBindings(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ProjectReleaseBinding], error) {
	ret := _m.Called(ctx, namespaceName, projectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectReleaseBindings")
	}

	var r0 *services.ListResult[v1alpha1.ProjectReleaseBinding]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectReleaseBinding], error)); ok {
		return rf(ctx, namespaceName, projectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.ProjectReleaseBinding]); ok {
		r0 = rf(ctx, namespaceName, projectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ProjectReleaseBinding])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, projectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListProjectReleaseBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectReleaseBindings'
type MockService_ListProjectReleaseBindings_Call struct {
	*mock.Call
}

// ListProjectReleaseBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListProjectReleaseBindings(ctx interface{}, namespaceName interface{}, projectName interface{}, opts interface{}) *MockService_ListProjectReleaseBindings_Call {
	return &MockService_ListProjectReleaseBindings_Call{Call: _e.mock.On("ListProjectReleaseBindings", ctx, namespaceName, projectName, opts)}
}

func (_c *MockService_ListProjectReleaseBindings_Call) Run(run func(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions)) *MockService_ListProjectReleaseBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListProjectReleaseBindings_Call) Return(_a0 *services.ListResult[v1alpha1.ProjectReleaseBinding], _a1 error) *MockService_ListProjectReleaseBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListProjectReleaseBindings_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectReleaseBinding], error)) *MockService_ListProjectReleaseBindings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) UpdateProjectReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectReleaseBinding")
	}

	var r0 *v1alpha1.ProjectReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) *v1alpha1.ProjectReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProjectReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateProjectReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectReleaseBinding'
type MockService_UpdateProjectReleaseBinding_Call struct {
	*mock.Call
}

// UpdateProjectReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ProjectReleaseBinding
func (_e *MockService_Expecter) UpdateProjectReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_UpdateProjectReleaseBinding_Call {
	return &MockService_UpdateProjectReleaseBinding_Call{Call: _e.mock.On("UpdateProjectReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_UpdateProjectReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ProjectReleaseBinding)) *MockService_UpdateProjectReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ProjectReleaseBinding))
	})
	return _c
}

func (_c *MockService_UpdateProjectReleaseBinding_Call) Return(_a0 *v1alpha1.ProjectReleaseBinding, _a1 error) *MockService_UpdateProjectReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateProjectReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ProjectReleaseBinding) (*v1alpha1.ProjectReleaseBinding, error)) *MockService_UpdateProjectReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
