// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/observer/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertIncidentService is an autogenerated mock type for the AlertIncidentService type
type MockAlertIncidentService struct {
	mock.Mock
}

type MockAlertIncidentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertIncidentService) EXPECT() *MockAlertIncidentService_Expecter {
	return &MockAlertIncidentService_Expecter{mock: &_m.Mock}
}

// IncidentScope provides a mock function with given fields: ctx, incidentID
func (_m *MockAlertIncidentService) IncidentScope(ctx context.Context, incidentID string) (string, string, string, error) {
	ret := _m.Called(ctx, incidentID)

	if len(ret) == 0 {
		panic("no return value specified for IncidentScope")
	}

	var r0 string
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, string, error)); ok {
		return rf(ctx, incidentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, incidentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, incidentID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) string); ok {
		r2 = rf(ctx, incidentID)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, incidentID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAlertIncidentService_IncidentScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncidentScope'
type MockAlertIncidentService_IncidentScope_Call struct {
	*mock.Call
}

// IncidentScope is a helper method to define mock.On call
//   - ctx context.Context
//   - incidentID string
func (_e *MockAlertIncidentService_Expecter) IncidentScope(ctx interface{}, incidentID interface{}) *MockAlertIncidentService_IncidentScope_Call {
	return &MockAlertIncidentService_IncidentScope_Call{Call: _e.mock.On("IncidentScope", ctx, incidentID)}
}

func (_c *MockAlertIncidentService_IncidentScope_Call) Run(run func(ctx context.Context, incidentID string)) *MockAlertIncidentService_IncidentScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAlertIncidentService_IncidentScope_Call) Return(namespace string, project string, component string, err error) *MockAlertIncidentService_IncidentScope_Call {
	_c.Call.Return(namespace, project, component, err)
	return _c
}

func (_c *MockAlertIncidentService_IncidentScope_Call) RunAndReturn(run func(context.Context, string) (string, string, string, error)) *MockAlertIncidentService_IncidentScope_Call {
	_c.Call.Return(run)
	return _c
}

// QueryAlerts provides a mock function with given fields: ctx, req
func (_m *MockAlertIncidentService) QueryAlerts(ctx context.Context, req gen.AlertsQueryRequest) (*gen.AlertsQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryAlerts")
	}

	var r0 *gen.AlertsQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.AlertsQueryRequest) (*gen.AlertsQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.AlertsQueryRequest) *gen.AlertsQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.AlertsQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.AlertsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertIncidentService_QueryAlerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAlerts'
type MockAlertIncidentService_QueryAlerts_Call struct {
	*mock.Call
}

// QueryAlerts is a helper method to define mock.On call
//   - ctx context.Context
//   - req gen.AlertsQueryRequest
func (_e *MockAlertIncidentService_Expecter) QueryAlerts(ctx interface{}, req interface{}) *MockAlertIncidentService_QueryAlerts_Call {
	return &MockAlertIncidentService_QueryAlerts_Call{Call: _e.mock.On("QueryAlerts", ctx, req)}
}

func (_c *MockAlertIncidentService_QueryAlerts_Call) Run(run func(ctx context.Context, req gen.AlertsQueryRequest)) *MockAlertIncidentService_QueryAlerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.AlertsQueryRequest))
	})
	return _c
}

func (_c *MockAlertIncidentService_QueryAlerts_Call) Return(_a0 *gen.AlertsQueryResponse, _a1 error) *MockAlertIncidentService_QueryAlerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertIncidentService_QueryAlerts_Call) RunAndReturn(run func(context.Context, gen.AlertsQueryRequest) (*gen.AlertsQueryResponse, error)) *MockAlertIncidentService_QueryAlerts_Call {
	_c.Call.Return(run)
	return _c
}

// QueryIncidents provides a mock function with given fields: ctx, req
func (_m *MockAlertIncidentService) QueryIncidents(ctx context.Context, req gen.IncidentsQueryRequest) (*gen.IncidentsQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryIncidents")
	}

	var r0 *gen.IncidentsQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.IncidentsQueryRequest) (*gen.IncidentsQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.IncidentsQueryRequest) *gen.IncidentsQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.IncidentsQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.IncidentsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertIncidentService_QueryIncidents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryIncidents'
type MockAlertIncidentService_QueryIncidents_Call struct {
	*mock.Call
}

// QueryIncidents is a helper method to define mock.On call
//   - ctx context.Context
//   - req gen.IncidentsQueryRequest
func (_e *MockAlertIncidentService_Expecter) QueryIncidents(ctx interface{}, req interface{}) *MockAlertIncidentService_QueryIncidents_Call {
	return &MockAlertIncidentService_QueryIncidents_Call{Call: _e.mock.On("QueryIncidents", ctx, req)}
}

func (_c *MockAlertIncidentService_QueryIncidents_Call) Run(run func(ctx context.Context, req gen.IncidentsQueryRequest)) *MockAlertIncidentService_QueryIncidents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.IncidentsQueryRequest))
	})
	return _c
}

func (_c *MockAlertIncidentService_QueryIncidents_Call) Return(_a0 *gen.IncidentsQueryResponse, _a1 error) *MockAlertIncidentService_QueryIncidents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertIncidentService_QueryIncidents_Call) RunAndReturn(run func(context.Context, gen.IncidentsQueryRequest) (*gen.IncidentsQueryResponse, error)) *MockAlertIncidentService_QueryIncidents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIncident provides a mock function with given fields: ctx, incidentID, req
func (_m *MockAlertIncidentService) UpdateIncident(ctx context.Context, incidentID string, req gen.IncidentPutRequest) (*gen.IncidentPutResponse, error) {
	ret := _m.Called(ctx, incidentID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIncident")
	}

	var r0 *gen.IncidentPutResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.IncidentPutRequest) (*gen.IncidentPutResponse, error)); ok {
		return rf(ctx, incidentID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.IncidentPutRequest) *gen.IncidentPutResponse); ok {
		r0 = rf(ctx, incidentID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.IncidentPutResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, gen.IncidentPutRequest) error); ok {
		r1 = rf(ctx, incidentID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertIncidentService_UpdateIncident_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIncident'
type MockAlertIncidentService_UpdateIncident_Call struct {
	*mock.Call
}

// UpdateIncident is a helper method to define mock.On call
//   - ctx context.Context
//   - incidentID string
//   - req gen.IncidentPutRequest
func (_e *MockAlertIncidentService_Expecter) UpdateIncident(ctx interface{}, incidentID interface{}, req interface{}) *MockAlertIncidentService_UpdateIncident_Call {
	return &MockAlertIncidentService_UpdateIncident_Call{Call: _e.mock.On("UpdateIncident", ctx, incidentID, req)}
}

func (_c *MockAlertIncidentService_UpdateIncident_Call) Run(run func(ctx context.Context, incidentID string, req gen.IncidentPutRequest)) *MockAlertIncidentService_UpdateIncident_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(gen.IncidentPutRequest))
	})
	return _c
}

func (_c *MockAlertIncidentService_UpdateIncident_Call) Return(_a0 *gen.IncidentPutResponse, _a1 error) *MockAlertIncidentService_UpdateIncident_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertIncidentService_UpdateIncident_Call) RunAndReturn(run func(context.Context, string, gen.IncidentPutRequest) (*gen.IncidentPutResponse, error)) *MockAlertIncidentService_UpdateIncident_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertIncidentService creates a new instance of MockAlertIncidentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertIncidentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertIncidentService {
	mock := &MockAlertIncidentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
