// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	internalgen "github.com/openchoreo/openchoreo/internal/observer/api/internalgen"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertRuleService is an autogenerated mock type for the AlertRuleService type
type MockAlertRuleService struct {
	mock.Mock
}

type MockAlertRuleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlertRuleService) EXPECT() *MockAlertRuleService_Expecter {
	return &MockAlertRuleService_Expecter{mock: &_m.Mock}
}

// CreateAlertRule provides a mock function with given fields: ctx, req
func (_m *MockAlertRuleService) CreateAlertRule(ctx context.Context, req internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAlertRule")
	}

	var r0 *internalgen.AlertingRuleSyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internalgen.AlertRuleRequest) *internalgen.AlertingRuleSyncResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgen.AlertingRuleSyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internalgen.AlertRuleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleService_CreateAlertRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAlertRule'
type MockAlertRuleService_CreateAlertRule_Call struct {
	*mock.Call
}

// CreateAlertRule is a helper method to define mock.On call
//   - ctx context.Context
//   - req internalgen.AlertRuleRequest
func (_e *MockAlertRuleService_Expecter) CreateAlertRule(ctx interface{}, req interface{}) *MockAlertRuleService_CreateAlertRule_Call {
	return &MockAlertRuleService_CreateAlertRule_Call{Call: _e.mock.On("CreateAlertRule", ctx, req)}
}

func (_c *MockAlertRuleService_CreateAlertRule_Call) Run(run func(ctx context.Context, req internalgen.AlertRuleRequest)) *MockAlertRuleService_CreateAlertRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internalgen.AlertRuleRequest))
	})
	return _c
}

func (_c *MockAlertRuleService_CreateAlertRule_Call) Return(_a0 *internalgen.AlertingRuleSyncResponse, _a1 error) *MockAlertRuleService_CreateAlertRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleService_CreateAlertRule_Call) RunAndReturn(run func(context.Context, internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error)) *MockAlertRuleService_CreateAlertRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAlertRule provides a mock function with given fields: ctx, ruleName, sourceType
func (_m *MockAlertRuleService) DeleteAlertRule(ctx context.Context, ruleName string, sourceType string) (*internalgen.AlertingRuleSyncResponse, error) {
	ret := _m.Called(ctx, ruleName, sourceType)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAlertRule")
	}

	var r0 *internalgen.AlertingRuleSyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*internalgen.AlertingRuleSyncResponse, error)); ok {
		return rf(ctx, ruleName, sourceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *internalgen.AlertingRuleSyncResponse); ok {
		r0 = rf(ctx, ruleName, sourceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgen.AlertingRuleSyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ruleName, sourceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleService_DeleteAlertRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAlertRule'
type MockAlertRuleService_DeleteAlertRule_Call struct {
	*mock.Call
}

// DeleteAlertRule is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleName string
//   - sourceType string
func (_e *MockAlertRuleService_Expecter) DeleteAlertRule(ctx interface{}, ruleName interface{}, sourceType interface{}) *MockAlertRuleService_DeleteAlertRule_Call {
	return &MockAlertRuleService_DeleteAlertRule_Call{Call: _e.mock.On("DeleteAlertRule", ctx, ruleName, sourceType)}
}

func (_c *MockAlertRuleService_DeleteAlertRule_Call) Run(run func(ctx context.Context, ruleName string, sourceType string)) *MockAlertRuleService_DeleteAlertRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAlertRuleService_DeleteAlertRule_Call) Return(_a0 *internalgen.AlertingRuleSyncResponse, _a1 error) *MockAlertRuleService_DeleteAlertRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleService_DeleteAlertRule_Call) RunAndReturn(run func(context.Context, string, string) (*internalgen.AlertingRuleSyncResponse, error)) *MockAlertRuleService_DeleteAlertRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetAlertRule provides a mock function with given fields: ctx, ruleName, sourceType
func (_m *MockAlertRuleService) GetAlertRule(ctx context.Context, ruleName string, sourceType string) (*internalgen.AlertRuleResponse, error) {
	ret := _m.Called(ctx, ruleName, sourceType)

	if len(ret) == 0 {
		panic("no return value specified for GetAlertRule")
	}

	var r0 *internalgen.AlertRuleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*internalgen.AlertRuleResponse, error)); ok {
		return rf(ctx, ruleName, sourceType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *internalgen.AlertRuleResponse); ok {
		r0 = rf(ctx, ruleName, sourceType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgen.AlertRuleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, ruleName, sourceType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleService_GetAlertRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAlertRule'
type MockAlertRuleService_GetAlertRule_Call struct {
	*mock.Call
}

// GetAlertRule is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleName string
//   - sourceType string
func (_e *MockAlertRuleService_Expecter) GetAlertRule(ctx interface{}, ruleName interface{}, sourceType interface{}) *MockAlertRuleService_GetAlertRule_Call {
	return &MockAlertRuleService_GetAlertRule_Call{Call: _e.mock.On("GetAlertRule", ctx, ruleName, sourceType)}
}

func (_c *MockAlertRuleService_GetAlertRule_Call) Run(run func(ctx context.Context, ruleName string, sourceType string)) *MockAlertRuleService_GetAlertRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAlertRuleService_GetAlertRule_Call) Return(_a0 *internalgen.AlertRuleResponse, _a1 error) *MockAlertRuleService_GetAlertRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleService_GetAlertRule_Call) RunAndReturn(run func(context.Context, string, string) (*internalgen.AlertRuleResponse, error)) *MockAlertRuleService_GetAlertRule_Call {
	_c.Call.Return(run)
	return _c
}

// HandleAlertWebhook provides a mock function with given fields: ctx, req
func (_m *MockAlertRuleService) HandleAlertWebhook(ctx context.Context, req internalgen.AlertWebhookRequest) (*internalgen.AlertWebhookResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleAlertWebhook")
	}

	var r0 *internalgen.AlertWebhookResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, internalgen.AlertWebhookRequest) (*internalgen.AlertWebhookResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, internalgen.AlertWebhookRequest) *internalgen.AlertWebhookResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgen.AlertWebhookResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, internalgen.AlertWebhookRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleService_HandleAlertWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleAlertWebhook'
type MockAlertRuleService_HandleAlertWebhook_Call struct {
	*mock.Call
}

// HandleAlertWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - req internalgen.AlertWebhookRequest
func (_e *MockAlertRuleService_Expecter) HandleAlertWebhook(ctx interface{}, req interface{}) *MockAlertRuleService_HandleAlertWebhook_Call {
	return &MockAlertRuleService_HandleAlertWebhook_Call{Call: _e.mock.On("HandleAlertWebhook", ctx, req)}
}

func (_c *MockAlertRuleService_HandleAlertWebhook_Call) Run(run func(ctx context.Context, req internalgen.AlertWebhookRequest)) *MockAlertRuleService_HandleAlertWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(internalgen.AlertWebhookRequest))
	})
	return _c
}

func (_c *MockAlertRuleService_HandleAlertWebhook_Call) Return(_a0 *internalgen.AlertWebhookResponse, _a1 error) *MockAlertRuleService_HandleAlertWebhook_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleService_HandleAlertWebhook_Call) RunAndReturn(run func(context.Context, internalgen.AlertWebhookRequest) (*internalgen.AlertWebhookResponse, error)) *MockAlertRuleService_HandleAlertWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlertRule provides a mock function with given fields: ctx, ruleName, req
func (_m *MockAlertRuleService) UpdateAlertRule(ctx context.Context, ruleName string, req internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error) {
	ret := _m.Called(ctx, ruleName, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlertRule")
	}

	var r0 *internalgen.AlertingRuleSyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error)); ok {
		return rf(ctx, ruleName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, internalgen.AlertRuleRequest) *internalgen.AlertingRuleSyncResponse); ok {
		r0 = rf(ctx, ruleName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internalgen.AlertingRuleSyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, internalgen.AlertRuleRequest) error); ok {
		r1 = rf(ctx, ruleName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlertRuleService_UpdateAlertRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlertRule'
type MockAlertRuleService_UpdateAlertRule_Call struct {
	*mock.Call
}

// UpdateAlertRule is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleName string
//   - req internalgen.AlertRuleRequest
func (_e *MockAlertRuleService_Expecter) UpdateAlertRule(ctx interface{}, ruleName interface{}, req interface{}) *MockAlertRuleService_UpdateAlertRule_Call {
	return &MockAlertRuleService_UpdateAlertRule_Call{Call: _e.mock.On("UpdateAlertRule", ctx, ruleName, req)}
}

func (_c *MockAlertRuleService_UpdateAlertRule_Call) Run(run func(ctx context.Context, ruleName string, req internalgen.AlertRuleRequest)) *MockAlertRuleService_UpdateAlertRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(internalgen.AlertRuleRequest))
	})
	return _c
}

func (_c *MockAlertRuleService_UpdateAlertRule_Call) Return(_a0 *internalgen.AlertingRuleSyncResponse, _a1 error) *MockAlertRuleService_UpdateAlertRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlertRuleService_UpdateAlertRule_Call) RunAndReturn(run func(context.Context, string, internalgen.AlertRuleRequest) (*internalgen.AlertingRuleSyncResponse, error)) *MockAlertRuleService_UpdateAlertRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlertRuleService creates a new instance of MockAlertRuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertRuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertRuleService {
	mock := &MockAlertRuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
