// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openchoreo/openchoreo/internal/observer/types"
)

// MockAuditLogsQuerier is an autogenerated mock type for the AuditLogsQuerier type
type MockAuditLogsQuerier struct {
	mock.Mock
}

type MockAuditLogsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogsQuerier) EXPECT() *MockAuditLogsQuerier_Expecter {
	return &MockAuditLogsQuerier_Expecter{mock: &_m.Mock}
}

// QueryAuditLogFilterValues provides a mock function with given fields: ctx, req
func (_m *MockAuditLogsQuerier) QueryAuditLogFilterValues(ctx context.Context, req *types.AuditLogFilterValuesRequest) (*types.AuditLogFilterValuesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryAuditLogFilterValues")
	}

	var r0 *types.AuditLogFilterValuesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.AuditLogFilterValuesRequest) (*types.AuditLogFilterValuesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.AuditLogFilterValuesRequest) *types.AuditLogFilterValuesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AuditLogFilterValuesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.AuditLogFilterValuesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuditLogsQuerier_QueryAuditLogFilterValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAuditLogFilterValues'
type MockAuditLogsQuerier_QueryAuditLogFilterValues_Call struct {
	*mock.Call
}

// QueryAuditLogFilterValues is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.AuditLogFilterValuesRequest
func (_e *MockAuditLogsQuerier_Expecter) QueryAuditLogFilterValues(ctx interface{}, req interface{}) *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call {
	return &MockAuditLogsQuerier_QueryAuditLogFilterValues_Call{Call: _e.mock.On("QueryAuditLogFilterValues", ctx, req)}
}

func (_c *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call) Run(run func(ctx context.Context, req *types.AuditLogFilterValuesRequest)) *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.AuditLogFilterValuesRequest))
	})
	return _c
}

func (_c *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call) Return(_a0 *types.AuditLogFilterValuesResponse, _a1 error) *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call) RunAndReturn(run func(context.Context, *types.AuditLogFilterValuesRequest) (*types.AuditLogFilterValuesResponse, error)) *MockAuditLogsQuerier_QueryAuditLogFilterValues_Call {
	_c.Call.Return(run)
	return _c
}

// QueryAuditLogs provides a mock function with given fields: ctx, req
func (_m *MockAuditLogsQuerier) QueryAuditLogs(ctx context.Context, req *types.AuditLogsQueryRequest) (*types.AuditLogsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryAuditLogs")
	}

	var r0 *types.AuditLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.AuditLogsQueryRequest) (*types.AuditLogsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.AuditLogsQueryRequest) *types.AuditLogsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AuditLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.AuditLogsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuditLogsQuerier_QueryAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryAuditLogs'
type MockAuditLogsQuerier_QueryAuditLogs_Call struct {
	*mock.Call
}

// QueryAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.AuditLogsQueryRequest
func (_e *MockAuditLogsQuerier_Expecter) QueryAuditLogs(ctx interface{}, req interface{}) *MockAuditLogsQuerier_QueryAuditLogs_Call {
	return &MockAuditLogsQuerier_QueryAuditLogs_Call{Call: _e.mock.On("QueryAuditLogs", ctx, req)}
}

func (_c *MockAuditLogsQuerier_QueryAuditLogs_Call) Run(run func(ctx context.Context, req *types.AuditLogsQueryRequest)) *MockAuditLogsQuerier_QueryAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.AuditLogsQueryRequest))
	})
	return _c
}

func (_c *MockAuditLogsQuerier_QueryAuditLogs_Call) Return(_a0 *types.AuditLogsResponse, _a1 error) *MockAuditLogsQuerier_QueryAuditLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuditLogsQuerier_QueryAuditLogs_Call) RunAndReturn(run func(context.Context, *types.AuditLogsQueryRequest) (*types.AuditLogsResponse, error)) *MockAuditLogsQuerier_QueryAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogsQuerier creates a new instance of MockAuditLogsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogsQuerier {
	mock := &MockAuditLogsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
