// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openchoreo/openchoreo/internal/observer/types"
)

// MockFinOpsQuerier is an autogenerated mock type for the FinOpsQuerier type
type MockFinOpsQuerier struct {
	mock.Mock
}

type MockFinOpsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinOpsQuerier) EXPECT() *MockFinOpsQuerier_Expecter {
	return &MockFinOpsQuerier_Expecter{mock: &_m.Mock}
}

// GetComponentCosts provides a mock function with given fields: ctx, req
func (_m *MockFinOpsQuerier) GetComponentCosts(ctx context.Context, req *types.CostQueryRequest) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentCosts")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.CostQueryRequest) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.CostQueryRequest) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.CostQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFinOpsQuerier_GetComponentCosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentCosts'
type MockFinOpsQuerier_GetComponentCosts_Call struct {
	*mock.Call
}

// GetComponentCosts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.CostQueryRequest
func (_e *MockFinOpsQuerier_Expecter) GetComponentCosts(ctx interface{}, req interface{}) *MockFinOpsQuerier_GetComponentCosts_Call {
	return &MockFinOpsQuerier_GetComponentCosts_Call{Call: _e.mock.On("GetComponentCosts", ctx, req)}
}

func (_c *MockFinOpsQuerier_GetComponentCosts_Call) Run(run func(ctx context.Context, req *types.CostQueryRequest)) *MockFinOpsQuerier_GetComponentCosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.CostQueryRequest))
	})
	return _c
}

func (_c *MockFinOpsQuerier_GetComponentCosts_Call) Return(_a0 interface{}, _a1 error) *MockFinOpsQuerier_GetComponentCosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFinOpsQuerier_GetComponentCosts_Call) RunAndReturn(run func(context.Context, *types.CostQueryRequest) (interface{}, error)) *MockFinOpsQuerier_GetComponentCosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecommendations provides a mock function with given fields: ctx, req
func (_m *MockFinOpsQuerier) GetRecommendations(ctx context.Context, req *types.RecommendationQueryRequest) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetRecommendations")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.RecommendationQueryRequest) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.RecommendationQueryRequest) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.RecommendationQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFinOpsQuerier_GetRecommendations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecommendations'
type MockFinOpsQuerier_GetRecommendations_Call struct {
	*mock.Call
}

// GetRecommendations is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.RecommendationQueryRequest
func (_e *MockFinOpsQuerier_Expecter) GetRecommendations(ctx interface{}, req interface{}) *MockFinOpsQuerier_GetRecommendations_Call {
	return &MockFinOpsQuerier_GetRecommendations_Call{Call: _e.mock.On("GetRecommendations", ctx, req)}
}

func (_c *MockFinOpsQuerier_GetRecommendations_Call) Run(run func(ctx context.Context, req *types.RecommendationQueryRequest)) *MockFinOpsQuerier_GetRecommendations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.RecommendationQueryRequest))
	})
	return _c
}

func (_c *MockFinOpsQuerier_GetRecommendations_Call) Return(_a0 interface{}, _a1 error) *MockFinOpsQuerier_GetRecommendations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFinOpsQuerier_GetRecommendations_Call) RunAndReturn(run func(context.Context, *types.RecommendationQueryRequest) (interface{}, error)) *MockFinOpsQuerier_GetRecommendations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinOpsQuerier creates a new instance of MockFinOpsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinOpsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinOpsQuerier {
	mock := &MockFinOpsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
