// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openchoreo/openchoreo/internal/observer/types"
)

// MockTracesQuerier is an autogenerated mock type for the TracesQuerier type
type MockTracesQuerier struct {
	mock.Mock
}

type MockTracesQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracesQuerier) EXPECT() *MockTracesQuerier_Expecter {
	return &MockTracesQuerier_Expecter{mock: &_m.Mock}
}

// GetSpanDetails provides a mock function with given fields: ctx, traceID, spanID
func (_m *MockTracesQuerier) GetSpanDetails(ctx context.Context, traceID string, spanID string) (*types.SpanInfo, error) {
	ret := _m.Called(ctx, traceID, spanID)

	if len(ret) == 0 {
		panic("no return value specified for GetSpanDetails")
	}

	var r0 *types.SpanInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*types.SpanInfo, error)); ok {
		return rf(ctx, traceID, spanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *types.SpanInfo); ok {
		r0 = rf(ctx, traceID, spanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.SpanInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, traceID, spanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracesQuerier_GetSpanDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpanDetails'
type MockTracesQuerier_GetSpanDetails_Call struct {
	*mock.Call
}

// GetSpanDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - traceID string
//   - spanID string
func (_e *MockTracesQuerier_Expecter) GetSpanDetails(ctx interface{}, traceID interface{}, spanID interface{}) *MockTracesQuerier_GetSpanDetails_Call {
	return &MockTracesQuerier_GetSpanDetails_Call{Call: _e.mock.On("GetSpanDetails", ctx, traceID, spanID)}
}

func (_c *MockTracesQuerier_GetSpanDetails_Call) Run(run func(ctx context.Context, traceID string, spanID string)) *MockTracesQuerier_GetSpanDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTracesQuerier_GetSpanDetails_Call) Return(_a0 *types.SpanInfo, _a1 error) *MockTracesQuerier_GetSpanDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracesQuerier_GetSpanDetails_Call) RunAndReturn(run func(context.Context, string, string) (*types.SpanInfo, error)) *MockTracesQuerier_GetSpanDetails_Call {
	_c.Call.Return(run)
	return _c
}

// QuerySpans provides a mock function with given fields: ctx, traceID, req
func (_m *MockTracesQuerier) QuerySpans(ctx context.Context, traceID string, req *types.TracesQueryRequest) (*types.SpansQueryResponse, error) {
	ret := _m.Called(ctx, traceID, req)

	if len(ret) == 0 {
		panic("no return value specified for QuerySpans")
	}

	var r0 *types.SpansQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.TracesQueryRequest) (*types.SpansQueryResponse, error)); ok {
		return rf(ctx, traceID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *types.TracesQueryRequest) *types.SpansQueryResponse); ok {
		r0 = rf(ctx, traceID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.SpansQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *types.TracesQueryRequest) error); ok {
		r1 = rf(ctx, traceID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracesQuerier_QuerySpans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuerySpans'
type MockTracesQuerier_QuerySpans_Call struct {
	*mock.Call
}

// QuerySpans is a helper method to define mock.On call
//   - ctx context.Context
//   - traceID string
//   - req *types.TracesQueryRequest
func (_e *MockTracesQuerier_Expecter) QuerySpans(ctx interface{}, traceID interface{}, req interface{}) *MockTracesQuerier_QuerySpans_Call {
	return &MockTracesQuerier_QuerySpans_Call{Call: _e.mock.On("QuerySpans", ctx, traceID, req)}
}

func (_c *MockTracesQuerier_QuerySpans_Call) Run(run func(ctx context.Context, traceID string, req *types.TracesQueryRequest)) *MockTracesQuerier_QuerySpans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*types.TracesQueryRequest))
	})
	return _c
}

func (_c *MockTracesQuerier_QuerySpans_Call) Return(_a0 *types.SpansQueryResponse, _a1 error) *MockTracesQuerier_QuerySpans_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracesQuerier_QuerySpans_Call) RunAndReturn(run func(context.Context, string, *types.TracesQueryRequest) (*types.SpansQueryResponse, error)) *MockTracesQuerier_QuerySpans_Call {
	_c.Call.Return(run)
	return _c
}

// QueryTraces provides a mock function with given fields: ctx, req
func (_m *MockTracesQuerier) QueryTraces(ctx context.Context, req *types.TracesQueryRequest) (*types.TracesQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryTraces")
	}

	var r0 *types.TracesQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.TracesQueryRequest) (*types.TracesQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.TracesQueryRequest) *types.TracesQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.TracesQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.TracesQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTracesQuerier_QueryTraces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryTraces'
type MockTracesQuerier_QueryTraces_Call struct {
	*mock.Call
}

// QueryTraces is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.TracesQueryRequest
func (_e *MockTracesQuerier_Expecter) QueryTraces(ctx interface{}, req interface{}) *MockTracesQuerier_QueryTraces_Call {
	return &MockTracesQuerier_QueryTraces_Call{Call: _e.mock.On("QueryTraces", ctx, req)}
}

func (_c *MockTracesQuerier_QueryTraces_Call) Run(run func(ctx context.Context, req *types.TracesQueryRequest)) *MockTracesQuerier_QueryTraces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.TracesQueryRequest))
	})
	return _c
}

func (_c *MockTracesQuerier_QueryTraces_Call) Return(_a0 *types.TracesQueryResponse, _a1 error) *MockTracesQuerier_QueryTraces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTracesQuerier_QueryTraces_Call) RunAndReturn(run func(context.Context, *types.TracesQueryRequest) (*types.TracesQueryResponse, error)) *MockTracesQuerier_QueryTraces_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTracesQuerier creates a new instance of MockTracesQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracesQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracesQuerier {
	mock := &MockTracesQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
