// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateProjectRelease provides a mock function with given fields: ctx, namespaceName, pr
func (_m *MockService) CreateProjectRelease(ctx context.Context, namespaceName string, pr *v1alpha1.ProjectRelease) (*v1alpha1.ProjectRelease, error) {
	ret := _m.Called(ctx, namespaceName, pr)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectRelease")
	}

	var r0 *v1alpha1.ProjectRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectRelease) (*v1alpha1.ProjectRelease, error)); ok {
		return rf(ctx, namespaceName, pr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectRelease) *v1alpha1.ProjectRelease); ok {
		r0 = rf(ctx, namespaceName, pr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProjectRelease) error); ok {
		r1 = rf(ctx, namespaceName, pr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateProjectRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectRelease'
type MockService_CreateProjectRelease_Call struct {
	*mock.Call
}

// CreateProjectRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - pr *v1alpha1.ProjectRelease
func (_e *MockService_Expecter) CreateProjectRelease(ctx interface{}, namespaceName interface{}, pr interface{}) *MockService_CreateProjectRelease_Call {
	return &MockService_CreateProjectRelease_Call{Call: _e.mock.On("CreateProjectRelease", ctx, namespaceName, pr)}
}

func (_c *MockService_CreateProjectRelease_Call) Run(run func(ctx context.Context, namespaceName string, pr *v1alpha1.ProjectRelease)) *MockService_CreateProjectRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ProjectRelease))
	})
	return _c
}

func (_c *MockService_CreateProjectRelease_Call) Return(_a0 *v1alpha1.ProjectRelease, _a1 error) *MockService_CreateProjectRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateProjectRelease_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ProjectRelease) (*v1alpha1.ProjectRelease, error)) *MockService_CreateProjectRelease_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectRelease provides a mock function with given fields: ctx, namespaceName, projectReleaseName
func (_m *MockService) DeleteProjectRelease(ctx context.Context, namespaceName string, projectReleaseName string) error {
	ret := _m.Called(ctx, namespaceName, projectReleaseName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, projectReleaseName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteProjectRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectRelease'
type MockService_DeleteProjectRelease_Call struct {
	*mock.Call
}

// DeleteProjectRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectReleaseName string
func (_e *MockService_Expecter) DeleteProjectRelease(ctx interface{}, namespaceName interface{}, projectReleaseName interface{}) *MockService_DeleteProjectRelease_Call {
	return &MockService_DeleteProjectRelease_Call{Call: _e.mock.On("DeleteProjectRelease", ctx, namespaceName, projectReleaseName)}
}

func (_c *MockService_DeleteProjectRelease_Call) Run(run func(ctx context.Context, namespaceName string, projectReleaseName string)) *MockService_DeleteProjectRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteProjectRelease_Call) Return(_a0 error) *MockService_DeleteProjectRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteProjectRelease_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteProjectRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectRelease provides a mock function with given fields: ctx, namespaceName, projectReleaseName
func (_m *MockService) GetProjectRelease(ctx context.Context, namespaceName string, projectReleaseName string) (*v1alpha1.ProjectRelease, error) {
	ret := _m.Called(ctx, namespaceName, projectReleaseName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectRelease")
	}

	var r0 *v1alpha1.ProjectRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ProjectRelease, error)); ok {
		return rf(ctx, namespaceName, projectReleaseName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ProjectRelease); ok {
		r0 = rf(ctx, namespaceName, projectReleaseName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, projectReleaseName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProjectRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectRelease'
type MockService_GetProjectRelease_Call struct {
	*mock.Call
}

// GetProjectRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectReleaseName string
func (_e *MockService_Expecter) GetProjectRelease(ctx interface{}, namespaceName interface{}, projectReleaseName interface{}) *MockService_GetProjectRelease_Call {
	return &MockService_GetProjectRelease_Call{Call: _e.mock.On("GetProjectRelease", ctx, namespaceName, projectReleaseName)}
}

func (_c *MockService_GetProjectRelease_Call) Run(run func(ctx context.Context, namespaceName string, projectReleaseName string)) *MockService_GetProjectRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetProjectRelease_Call) Return(_a0 *v1alpha1.ProjectRelease, _a1 error) *MockService_GetProjectRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProjectRelease_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ProjectRelease, error)) *MockService_GetProjectRelease_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectReleases provides a mock function with given fields: ctx, namespaceName, projectName, opts
func (_m *MockService) ListProjectReleases(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ProjectRelease], error) {
	ret := _m.Called(ctx, namespaceName, projectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectReleases")
	}

	var r0 *services.ListResult[v1alpha1.ProjectRelease]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectRelease], error)); ok {
		return rf(ctx, namespaceName, projectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.ProjectRelease]); ok {
		r0 = rf(ctx, namespaceName, projectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ProjectRelease])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, projectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListProjectReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectReleases'
type MockService_ListProjectReleases_Call struct {
	*mock.Call
}

// ListProjectReleases is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListProjectReleases(ctx interface{}, namespaceName interface{}, projectName interface{}, opts interface{}) *MockService_ListProjectReleases_Call {
	return &MockService_ListProjectReleases_Call{Call: _e.mock.On("ListProjectReleases", ctx, namespaceName, projectName, opts)}
}

func (_c *MockService_ListProjectReleases_Call) Run(run func(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions)) *MockService_ListProjectReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListProjectReleases_Call) Return(_a0 *services.ListResult[v1alpha1.ProjectRelease], _a1 error) *MockService_ListProjectReleases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListProjectReleases_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectRelease], error)) *MockService_ListProjectReleases_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
