// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/auditgen. DO NOT EDIT.

package audit

import (
	"github.com/openchoreo/openchoreo/internal/server/middleware/audit"
)

// generatedOperationDefs returns one audit.OperationDef per state-modifying
// REST operation in the OpenAPI spec, minus the operations in
// excludedOperationIDs. MCP fields are zero-valued here — mcp_bindings.go
// enriches specific entries by ID, since the MCP tool/scope/resource-arg
// mapping isn't derivable from the spec.
//
// Regenerate with: make code.gen (runs tools/auditgen).
func generatedOperationDefs() []audit.OperationDef {
	return []audit.OperationDef{
		{
			ID: "CreateClusterComponentType", Action: "create_cluster_component_type", ResourceType: "clustercomponenttype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterDataPlane", Action: "create_cluster_data_plane", ResourceType: "clusterdataplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterObservabilityPlane", Action: "create_cluster_observability_plane", ResourceType: "clusterobservabilityplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterProjectType", Action: "create_cluster_project_type", ResourceType: "clusterprojecttype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterResourceType", Action: "create_cluster_resource_type", ResourceType: "clusterresourcetype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterRole", Action: "create_cluster_role", ResourceType: "clusterauthzrole",
			Category: audit.CategoryAuthorization,
		},
		{
			ID: "CreateClusterRoleBinding", Action: "create_cluster_role_binding", ResourceType: "clusterauthzrolebinding",
			Category: audit.CategoryAuthorization,
		},
		{
			ID: "CreateClusterTrait", Action: "create_cluster_trait", ResourceType: "clustertrait",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterWorkflow", Action: "create_cluster_workflow", ResourceType: "clusterworkflow",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateClusterWorkflowPlane", Action: "create_cluster_workflow_plane", ResourceType: "clusterworkflowplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateComponent", Action: "create_component", ResourceType: "component",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateComponentRelease", Action: "create_component_release", ResourceType: "componentrelease",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateComponentType", Action: "create_component_type", ResourceType: "componenttype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateDataPlane", Action: "create_data_plane", ResourceType: "dataplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateDeploymentPipeline", Action: "create_deployment_pipeline", ResourceType: "deploymentpipeline",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateEnvironment", Action: "create_environment", ResourceType: "environment",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateGitSecret", Action: "create_git_secret", ResourceType: "gitsecret",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateNamespace", Action: "create_namespace", ResourceType: "namespace",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateNamespaceRole", Action: "create_namespace_role", ResourceType: "authzrole",
			Category: audit.CategoryAuthorization,
		},
		{
			ID: "CreateNamespaceRoleBinding", Action: "create_namespace_role_binding", ResourceType: "authzrolebinding",
			Category: audit.CategoryAuthorization,
		},
		{
			ID: "CreateObservabilityAlertsNotificationChannel", Action: "create_observability_alerts_notification_channel", ResourceType: "observabilityalertsnotificationchannel",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateObservabilityPlane", Action: "create_observability_plane", ResourceType: "observabilityplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateProject", Action: "create_project", ResourceType: "project",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateProjectRelease", Action: "create_project_release", ResourceType: "projectrelease",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateProjectReleaseBinding", Action: "create_project_release_binding", ResourceType: "projectreleasebinding",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateProjectType", Action: "create_project_type", ResourceType: "projecttype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateReleaseBinding", Action: "create_release_binding", ResourceType: "releasebinding",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateResource", Action: "create_resource", ResourceType: "resource",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateResourceRelease", Action: "create_resource_release", ResourceType: "resourcerelease",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateResourceReleaseBinding", Action: "create_resource_release_binding", ResourceType: "resourcereleasebinding",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateResourceType", Action: "create_resource_type", ResourceType: "resourcetype",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateSecret", Action: "create_secret", ResourceType: "secret",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateSecretReference", Action: "create_secret_reference", ResourceType: "secretreference",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateTrait", Action: "create_trait", ResourceType: "trait",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateWorkflow", Action: "create_workflow", ResourceType: "workflow",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateWorkflowPlane", Action: "create_workflow_plane", ResourceType: "workflowplane",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateWorkflowRun", Action: "create_workflow_run", ResourceType: "workflowrun",
			Category: audit.CategoryManagement,
		},
		{
			ID: "CreateWorkload", Action: "create_workload", ResourceType: "workload",
			Category: audit.CategoryManagement,
		},
		{
			ID: "DeleteClusterComponentType", Action: "delete_cluster_component_type", ResourceType: "clustercomponenttype",
			Category: audit.CategoryManagement, RESTResourceParam: "cctName",
		},
		{
			ID: "DeleteClusterDataPlane", Action: "delete_cluster_data_plane", ResourceType: "clusterdataplane",
			Category: audit.CategoryManagement, RESTResourceParam: "cdpName",
		},
		{
			ID: "DeleteClusterObservabilityPlane", Action: "delete_cluster_observability_plane", ResourceType: "clusterobservabilityplane",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterObservabilityPlaneName",
		},
		{
			ID: "DeleteClusterProjectType", Action: "delete_cluster_project_type", ResourceType: "clusterprojecttype",
			Category: audit.CategoryManagement, RESTResourceParam: "cptName",
		},
		{
			ID: "DeleteClusterResourceType", Action: "delete_cluster_resource_type", ResourceType: "clusterresourcetype",
			Category: audit.CategoryManagement, RESTResourceParam: "crtName",
		},
		{
			ID: "DeleteClusterRole", Action: "delete_cluster_role", ResourceType: "clusterauthzrole",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "DeleteClusterRoleBinding", Action: "delete_cluster_role_binding", ResourceType: "clusterauthzrolebinding",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "DeleteClusterTrait", Action: "delete_cluster_trait", ResourceType: "clustertrait",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterTraitName",
		},
		{
			ID: "DeleteClusterWorkflow", Action: "delete_cluster_workflow", ResourceType: "clusterworkflow",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterWorkflowName",
		},
		{
			ID: "DeleteClusterWorkflowPlane", Action: "delete_cluster_workflow_plane", ResourceType: "clusterworkflowplane",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterWorkflowPlaneName",
		},
		{
			ID: "DeleteComponent", Action: "delete_component", ResourceType: "component",
			Category: audit.CategoryManagement, RESTResourceParam: "componentName",
		},
		{
			ID: "DeleteComponentRelease", Action: "delete_component_release", ResourceType: "componentrelease",
			Category: audit.CategoryManagement, RESTResourceParam: "componentReleaseName",
		},
		{
			ID: "DeleteComponentType", Action: "delete_component_type", ResourceType: "componenttype",
			Category: audit.CategoryManagement, RESTResourceParam: "ctName",
		},
		{
			ID: "DeleteDataPlane", Action: "delete_data_plane", ResourceType: "dataplane",
			Category: audit.CategoryManagement, RESTResourceParam: "dpName",
		},
		{
			ID: "DeleteDeploymentPipeline", Action: "delete_deployment_pipeline", ResourceType: "deploymentpipeline",
			Category: audit.CategoryManagement, RESTResourceParam: "deploymentPipelineName",
		},
		{
			ID: "DeleteEnvironment", Action: "delete_environment", ResourceType: "environment",
			Category: audit.CategoryManagement, RESTResourceParam: "envName",
		},
		{
			ID: "DeleteGitSecret", Action: "delete_git_secret", ResourceType: "gitsecret",
			Category: audit.CategoryManagement, RESTResourceParam: "gitSecretName",
		},
		{
			ID: "DeleteNamespace", Action: "delete_namespace", ResourceType: "namespace",
			Category: audit.CategoryManagement, RESTResourceParam: "namespaceName",
		},
		{
			ID: "DeleteNamespaceRole", Action: "delete_namespace_role", ResourceType: "authzrole",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "DeleteNamespaceRoleBinding", Action: "delete_namespace_role_binding", ResourceType: "authzrolebinding",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "DeleteObservabilityAlertsNotificationChannel", Action: "delete_observability_alerts_notification_channel", ResourceType: "observabilityalertsnotificationchannel",
			Category: audit.CategoryManagement, RESTResourceParam: "observabilityAlertsNotificationChannelName",
		},
		{
			ID: "DeleteObservabilityPlane", Action: "delete_observability_plane", ResourceType: "observabilityplane",
			Category: audit.CategoryManagement, RESTResourceParam: "observabilityPlaneName",
		},
		{
			ID: "DeleteProject", Action: "delete_project", ResourceType: "project",
			Category: audit.CategoryManagement, RESTResourceParam: "projectName",
		},
		{
			ID: "DeleteProjectRelease", Action: "delete_project_release", ResourceType: "projectrelease",
			Category: audit.CategoryManagement, RESTResourceParam: "projectReleaseName",
		},
		{
			ID: "DeleteProjectReleaseBinding", Action: "delete_project_release_binding", ResourceType: "projectreleasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "projectReleaseBindingName",
		},
		{
			ID: "DeleteProjectType", Action: "delete_project_type", ResourceType: "projecttype",
			Category: audit.CategoryManagement, RESTResourceParam: "ptName",
		},
		{
			ID: "DeleteReleaseBinding", Action: "delete_release_binding", ResourceType: "releasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "releaseBindingName",
		},
		{
			ID: "DeleteResource", Action: "delete_resource", ResourceType: "resource",
			Category: audit.CategoryManagement, RESTResourceParam: "resourceName",
		},
		{
			ID: "DeleteResourceRelease", Action: "delete_resource_release", ResourceType: "resourcerelease",
			Category: audit.CategoryManagement, RESTResourceParam: "resourceReleaseName",
		},
		{
			ID: "DeleteResourceReleaseBinding", Action: "delete_resource_release_binding", ResourceType: "resourcereleasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "resourceReleaseBindingName",
		},
		{
			ID: "DeleteResourceType", Action: "delete_resource_type", ResourceType: "resourcetype",
			Category: audit.CategoryManagement, RESTResourceParam: "rtName",
		},
		{
			ID: "DeleteSecret", Action: "delete_secret", ResourceType: "secret",
			Category: audit.CategoryManagement, RESTResourceParam: "secretName",
		},
		{
			ID: "DeleteSecretReference", Action: "delete_secret_reference", ResourceType: "secretreference",
			Category: audit.CategoryManagement, RESTResourceParam: "secretReferenceName",
		},
		{
			ID: "DeleteTrait", Action: "delete_trait", ResourceType: "trait",
			Category: audit.CategoryManagement, RESTResourceParam: "traitName",
		},
		{
			ID: "DeleteWorkflow", Action: "delete_workflow", ResourceType: "workflow",
			Category: audit.CategoryManagement, RESTResourceParam: "workflowName",
		},
		{
			ID: "DeleteWorkflowPlane", Action: "delete_workflow_plane", ResourceType: "workflowplane",
			Category: audit.CategoryManagement, RESTResourceParam: "workflowPlaneName",
		},
		{
			ID: "DeleteWorkflowRun", Action: "delete_workflow_run", ResourceType: "workflowrun",
			Category: audit.CategoryManagement, RESTResourceParam: "runName",
		},
		{
			ID: "DeleteWorkload", Action: "delete_workload", ResourceType: "workload",
			Category: audit.CategoryManagement, RESTResourceParam: "workloadName",
		},
		{
			ID: "GenerateRelease", Action: "generate_release", ResourceType: "componentrelease",
			Category: audit.CategoryManagement,
		},
		{
			ID: "TriggerReleaseBindingCronJob", Action: "trigger_release_binding_cron_job", ResourceType: "releasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "releaseBindingName",
		},
		{
			ID: "UpdateClusterComponentType", Action: "update_cluster_component_type", ResourceType: "clustercomponenttype",
			Category: audit.CategoryManagement, RESTResourceParam: "cctName",
		},
		{
			ID: "UpdateClusterDataPlane", Action: "update_cluster_data_plane", ResourceType: "clusterdataplane",
			Category: audit.CategoryManagement, RESTResourceParam: "cdpName",
		},
		{
			ID: "UpdateClusterObservabilityPlane", Action: "update_cluster_observability_plane", ResourceType: "clusterobservabilityplane",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterObservabilityPlaneName",
		},
		{
			ID: "UpdateClusterProjectType", Action: "update_cluster_project_type", ResourceType: "clusterprojecttype",
			Category: audit.CategoryManagement, RESTResourceParam: "cptName",
		},
		{
			ID: "UpdateClusterResourceType", Action: "update_cluster_resource_type", ResourceType: "clusterresourcetype",
			Category: audit.CategoryManagement, RESTResourceParam: "crtName",
		},
		{
			ID: "UpdateClusterRole", Action: "update_cluster_role", ResourceType: "clusterauthzrole",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "UpdateClusterRoleBinding", Action: "update_cluster_role_binding", ResourceType: "clusterauthzrolebinding",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "UpdateClusterTrait", Action: "update_cluster_trait", ResourceType: "clustertrait",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterTraitName",
		},
		{
			ID: "UpdateClusterWorkflow", Action: "update_cluster_workflow", ResourceType: "clusterworkflow",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterWorkflowName",
		},
		{
			ID: "UpdateClusterWorkflowPlane", Action: "update_cluster_workflow_plane", ResourceType: "clusterworkflowplane",
			Category: audit.CategoryManagement, RESTResourceParam: "clusterWorkflowPlaneName",
		},
		{
			ID: "UpdateComponent", Action: "update_component", ResourceType: "component",
			Category: audit.CategoryManagement, RESTResourceParam: "componentName",
		},
		{
			ID: "UpdateComponentType", Action: "update_component_type", ResourceType: "componenttype",
			Category: audit.CategoryManagement, RESTResourceParam: "ctName",
		},
		{
			ID: "UpdateDataPlane", Action: "update_data_plane", ResourceType: "dataplane",
			Category: audit.CategoryManagement, RESTResourceParam: "dpName",
		},
		{
			ID: "UpdateDeploymentPipeline", Action: "update_deployment_pipeline", ResourceType: "deploymentpipeline",
			Category: audit.CategoryManagement, RESTResourceParam: "deploymentPipelineName",
		},
		{
			ID: "UpdateEnvironment", Action: "update_environment", ResourceType: "environment",
			Category: audit.CategoryManagement, RESTResourceParam: "envName",
		},
		{
			ID: "UpdateNamespace", Action: "update_namespace", ResourceType: "namespace",
			Category: audit.CategoryManagement, RESTResourceParam: "namespaceName",
		},
		{
			ID: "UpdateNamespaceRole", Action: "update_namespace_role", ResourceType: "authzrole",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "UpdateNamespaceRoleBinding", Action: "update_namespace_role_binding", ResourceType: "authzrolebinding",
			Category: audit.CategoryAuthorization, RESTResourceParam: "name",
		},
		{
			ID: "UpdateObservabilityAlertsNotificationChannel", Action: "update_observability_alerts_notification_channel", ResourceType: "observabilityalertsnotificationchannel",
			Category: audit.CategoryManagement, RESTResourceParam: "observabilityAlertsNotificationChannelName",
		},
		{
			ID: "UpdateObservabilityPlane", Action: "update_observability_plane", ResourceType: "observabilityplane",
			Category: audit.CategoryManagement, RESTResourceParam: "observabilityPlaneName",
		},
		{
			ID: "UpdateProject", Action: "update_project", ResourceType: "project",
			Category: audit.CategoryManagement, RESTResourceParam: "projectName",
		},
		{
			ID: "UpdateProjectReleaseBinding", Action: "update_project_release_binding", ResourceType: "projectreleasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "projectReleaseBindingName",
		},
		{
			ID: "UpdateProjectType", Action: "update_project_type", ResourceType: "projecttype",
			Category: audit.CategoryManagement, RESTResourceParam: "ptName",
		},
		{
			ID: "UpdateReleaseBinding", Action: "update_release_binding", ResourceType: "releasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "releaseBindingName",
		},
		{
			ID: "UpdateResource", Action: "update_resource", ResourceType: "resource",
			Category: audit.CategoryManagement, RESTResourceParam: "resourceName",
		},
		{
			ID: "UpdateResourceReleaseBinding", Action: "update_resource_release_binding", ResourceType: "resourcereleasebinding",
			Category: audit.CategoryManagement, RESTResourceParam: "resourceReleaseBindingName",
		},
		{
			ID: "UpdateResourceType", Action: "update_resource_type", ResourceType: "resourcetype",
			Category: audit.CategoryManagement, RESTResourceParam: "rtName",
		},
		{
			ID: "UpdateSecret", Action: "update_secret", ResourceType: "secret",
			Category: audit.CategoryManagement, RESTResourceParam: "secretName",
		},
		{
			ID: "UpdateSecretReference", Action: "update_secret_reference", ResourceType: "secretreference",
			Category: audit.CategoryManagement, RESTResourceParam: "secretReferenceName",
		},
		{
			ID: "UpdateTrait", Action: "update_trait", ResourceType: "trait",
			Category: audit.CategoryManagement, RESTResourceParam: "traitName",
		},
		{
			ID: "UpdateWorkflow", Action: "update_workflow", ResourceType: "workflow",
			Category: audit.CategoryManagement, RESTResourceParam: "workflowName",
		},
		{
			ID: "UpdateWorkflowPlane", Action: "update_workflow_plane", ResourceType: "workflowplane",
			Category: audit.CategoryManagement, RESTResourceParam: "workflowPlaneName",
		},
		{
			ID: "UpdateWorkflowRun", Action: "update_workflow_run", ResourceType: "workflowrun",
			Category: audit.CategoryManagement, RESTResourceParam: "runName",
		},
		{
			ID: "UpdateWorkload", Action: "update_workload", ResourceType: "workload",
			Category: audit.CategoryManagement, RESTResourceParam: "workloadName",
		},
	}
}
