// Package finopsadapterclientgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package finopsadapterclientgen

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ComponentCost defines model for ComponentCost.
type ComponentCost struct {
	// Component Human-readable component name. Not stable across renames.
	Component string `json:"component"`

	// ComponentUid UID of the component this record belongs to.
	ComponentUid openapi_types.UUID `json:"componentUid"`

	// CpuCost CPU cost for this record's window.
	CpuCost float32 `json:"cpuCost"`

	// Efficiency Cost-weighted blend of CPU and memory utilization for this
	// record's window. A value of 0.85 means 85% of what was paid for
	// was actually used.
	Efficiency float32 `json:"efficiency"`

	// EndTime Exclusive end of the window this record covers. Equals the request
	// `endTime` when no granularity is set; otherwise the end of the
	// time bucket.
	EndTime time.Time `json:"endTime"`

	// Environment Human-readable environment name.
	Environment    string             `json:"environment"`
	EnvironmentUid openapi_types.UUID `json:"environmentUid"`

	// MemoryCost Memory cost for this record's window.
	MemoryCost float32 `json:"memoryCost"`

	// Namespace Namespace name. OpenChoreo namespaces do not have UIDs, so the
	// name is used here.
	Namespace string `json:"namespace"`

	// Project Human-readable project name.
	Project    string             `json:"project"`
	ProjectUid openapi_types.UUID `json:"projectUid"`

	// StartTime Inclusive start of the window this record covers. Equals the
	// request `startTime` when no granularity is set; otherwise the
	// start of the time bucket.
	StartTime time.Time `json:"startTime"`
}

// ComponentRecommendation defines model for ComponentRecommendation.
type ComponentRecommendation struct {
	// Component Human-readable component name.
	Component    string             `json:"component"`
	ComponentUid openapi_types.UUID `json:"componentUid"`

	// Current Resource requests, limits, and resulting cost. Resource fields use
	// Kubernetes quantity notation as strings (e.g. `"230m"` for CPU
	// millicores, `"250Mi"` for memory).
	Current ResourceProfile `json:"current"`

	// Environment Human-readable environment name.
	Environment    string             `json:"environment"`
	EnvironmentUid openapi_types.UUID `json:"environmentUid"`
	Namespace      string             `json:"namespace"`

	// Project Human-readable project name.
	Project    string             `json:"project"`
	ProjectUid openapi_types.UUID `json:"projectUid"`

	// Recommendation Resource requests, limits, and resulting cost. Resource fields use
	// Kubernetes quantity notation as strings (e.g. `"230m"` for CPU
	// millicores, `"250Mi"` for memory).
	Recommendation ResourceProfile `json:"recommendation"`
}

// CostResponse defines model for CostResponse.
type CostResponse struct {
	// Items Flat list of per-component cost records. Without `granularity`,
	// one record per component. With `granularity`, one record per
	// component per time bucket.
	Items []ComponentCost `json:"items"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// RecommendationResponse defines model for RecommendationResponse.
type RecommendationResponse struct {
	// Items One recommendation per component in scope. A single element when
	// `componentUid` is specified; one per component in the project
	// otherwise. Uses the same array envelope as the cost endpoint.
	Items []ComponentRecommendation `json:"items"`
}

// ResourceProfile Resource requests, limits, and resulting cost. Resource fields use
// Kubernetes quantity notation as strings (e.g. `"230m"` for CPU
// millicores, `"250Mi"` for memory).
type ResourceProfile struct {
	// CpuCost CPU cost for the selected time window at these resource settings.
	CpuCost    float32 `json:"cpuCost"`
	CpuLimit   string  `json:"cpuLimit"`
	CpuRequest string  `json:"cpuRequest"`

	// MemoryCost Memory cost for the selected time window at these resource
	// settings.
	MemoryCost    float32 `json:"memoryCost"`
	MemoryLimit   string  `json:"memoryLimit"`
	MemoryRequest string  `json:"memoryRequest"`
}

// ComponentUid defines model for ComponentUid.
type ComponentUid = openapi_types.UUID

// EndTime defines model for EndTime.
type EndTime = time.Time

// EnvironmentUid defines model for EnvironmentUid.
type EnvironmentUid = openapi_types.UUID

// Granularity defines model for Granularity.
type Granularity = string

// Namespace defines model for Namespace.
type Namespace = string

// ProjectUid defines model for ProjectUid.
type ProjectUid = openapi_types.UUID

// StartTime defines model for StartTime.
type StartTime = time.Time

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetComponentCostsParams defines parameters for GetComponentCosts.
type GetComponentCostsParams struct {
	// ProjectUid Project UID. When set, narrows the response to components in this
	// project.
	ProjectUid *ProjectUid `form:"projectUid,omitempty" json:"projectUid,omitempty"`

	// ComponentUid Component UID. When set, narrows the response to this single component.
	// Requires `projectUid` to also be set.
	ComponentUid *ComponentUid `form:"componentUid,omitempty" json:"componentUid,omitempty"`

	// StartTime Inclusive lower bound of the cost window. RFC 3339 timestamp with
	// second precision (sub-second components are not supported and will
	// be rejected).
	StartTime StartTime `form:"startTime" json:"startTime"`

	// EndTime Exclusive upper bound of the cost window. RFC 3339 timestamp with
	// second precision (sub-second components are not supported and will
	// be rejected). Must be strictly greater than `startTime`.
	EndTime EndTime `form:"endTime" json:"endTime"`

	// Granularity When present, each component is split into one record per time bucket
	// of this size. Records with the same `componentUid` and differing time
	// windows represent that component across multiple buckets.
	//
	// The value uses `<count><unit>` notation, where `count` is a positive
	// integer and `unit` is one of `h` (hours), `d` (days), or `w` (weeks).
	// For example: `1h`, `2d`, `3w`.
	Granularity *Granularity `form:"granularity,omitempty" json:"granularity,omitempty"`
}

// GetRecommendationsParams defines parameters for GetRecommendations.
type GetRecommendationsParams struct {
	// StartTime Inclusive lower bound of the cost window. RFC 3339 timestamp with
	// second precision (sub-second components are not supported and will
	// be rejected).
	StartTime StartTime `form:"startTime" json:"startTime"`

	// EndTime Exclusive upper bound of the cost window. RFC 3339 timestamp with
	// second precision (sub-second components are not supported and will
	// be rejected). Must be strictly greater than `startTime`.
	EndTime EndTime `form:"endTime" json:"endTime"`

	// ProjectUid Project UID. When set, narrows the result to components in this
	// project. When omitted, recommendations for all components in the
	// environment are returned.
	ProjectUid *openapi_types.UUID `form:"projectUid,omitempty" json:"projectUid,omitempty"`

	// ComponentUid Component UID. When set, narrows the result to this single
	// component. Requires `projectUid` to also be set.
	ComponentUid *openapi_types.UUID `form:"componentUid,omitempty" json:"componentUid,omitempty"`

	// Environment Environment name. Required for the same reason as `namespace`.
	Environment string `form:"environment" json:"environment"`

	// Project Project name. Required only when `projectUid` is supplied, since
	// the adapter needs it for the name-based metrics call.
	Project *string `form:"project,omitempty" json:"project,omitempty"`

	// Component Component name. Required only when `componentUid` is supplied,
	// since the adapter needs it for the name-based metrics call.
	Component *string `form:"component,omitempty" json:"component,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetComponentCosts request
	GetComponentCosts(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetComponentCostsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecommendations request
	GetRecommendations(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetRecommendationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetComponentCosts(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetComponentCostsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetComponentCostsRequest(c.Server, namespace, environmentUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRecommendations(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetRecommendationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecommendationsRequest(c.Server, namespace, environmentUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetComponentCostsRequest generates requests for GetComponentCosts
func NewGetComponentCostsRequest(server string, namespace Namespace, environmentUid EnvironmentUid, params *GetComponentCostsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentUid", runtime.ParamLocationPath, environmentUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/costs/namespaces/%s/environments/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ProjectUid != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectUid", runtime.ParamLocationQuery, *params.ProjectUid); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ComponentUid != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "componentUid", runtime.ParamLocationQuery, *params.ComponentUid); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "startTime", runtime.ParamLocationQuery, params.StartTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "endTime", runtime.ParamLocationQuery, params.EndTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Granularity != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "granularity", runtime.ParamLocationQuery, *params.Granularity); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRecommendationsRequest generates requests for GetRecommendations
func NewGetRecommendationsRequest(server string, namespace Namespace, environmentUid EnvironmentUid, params *GetRecommendationsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "namespace", runtime.ParamLocationPath, namespace)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "environmentUid", runtime.ParamLocationPath, environmentUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1alpha1/costs/namespaces/%s/environments/%s/recommendations", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "startTime", runtime.ParamLocationQuery, params.StartTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "endTime", runtime.ParamLocationQuery, params.EndTime); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.ProjectUid != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectUid", runtime.ParamLocationQuery, *params.ProjectUid); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ComponentUid != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "componentUid", runtime.ParamLocationQuery, *params.ComponentUid); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "environment", runtime.ParamLocationQuery, params.Environment); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Project != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project", runtime.ParamLocationQuery, *params.Project); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Component != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "component", runtime.ParamLocationQuery, *params.Component); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetComponentCostsWithResponse request
	GetComponentCostsWithResponse(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetComponentCostsParams, reqEditors ...RequestEditorFn) (*GetComponentCostsResp, error)

	// GetRecommendationsWithResponse request
	GetRecommendationsWithResponse(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetRecommendationsParams, reqEditors ...RequestEditorFn) (*GetRecommendationsResp, error)
}

type GetComponentCostsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CostResponse
	JSON400      *BadRequest
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetComponentCostsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetComponentCostsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRecommendationsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecommendationResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON404      *NotFound
	JSON500      *InternalError
}

// Status returns HTTPResponse.Status
func (r GetRecommendationsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecommendationsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetComponentCostsWithResponse request returning *GetComponentCostsResp
func (c *ClientWithResponses) GetComponentCostsWithResponse(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetComponentCostsParams, reqEditors ...RequestEditorFn) (*GetComponentCostsResp, error) {
	rsp, err := c.GetComponentCosts(ctx, namespace, environmentUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetComponentCostsResp(rsp)
}

// GetRecommendationsWithResponse request returning *GetRecommendationsResp
func (c *ClientWithResponses) GetRecommendationsWithResponse(ctx context.Context, namespace Namespace, environmentUid EnvironmentUid, params *GetRecommendationsParams, reqEditors ...RequestEditorFn) (*GetRecommendationsResp, error) {
	rsp, err := c.GetRecommendations(ctx, namespace, environmentUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecommendationsResp(rsp)
}

// ParseGetComponentCostsResp parses an HTTP response from a GetComponentCostsWithResponse call
func ParseGetComponentCostsResp(rsp *http.Response) (*GetComponentCostsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetComponentCostsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CostResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetRecommendationsResp parses an HTTP response from a GetRecommendationsWithResponse call
func ParseGetRecommendationsResp(rsp *http.Response) (*GetRecommendationsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecommendationsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecommendationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
