// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterTraitSpec defines the desired state of ClusterTrait.
// +kubebuilder:validation:XValidation:rule="!(has(self.validations) && size(self.validations) > 0 && has(self.preRenderValidations) && size(self.preRenderValidations) > 0)",message="set only one of spec.validations or spec.preRenderValidations; validations is deprecated, use preRenderValidations"
type ClusterTraitSpec struct {
	// Parameters defines developer-facing configuration options for this trait.
	// +optional
	Parameters *SchemaSection `json:"parameters,omitempty"`

	// EnvironmentConfigs defines per-environment configurations for this trait via ReleaseBinding.
	// +optional
	EnvironmentConfigs *SchemaSection `json:"environmentConfigs,omitempty"`

	// Validations are CEL-based rules evaluated before rendering.
	//
	// Deprecated: use PreRenderValidations. Retained for backward compatibility;
	// it is mutually exclusive with PreRenderValidations and has identical semantics.
	// +optional
	Validations []ValidationRule `json:"validations,omitempty"`

	// PreRenderValidations are CEL-based rules evaluated before rendering, against
	// the trait's static parameters/environmentConfigs/metadata context.
	// All rules must evaluate to true for rendering to proceed. Replaces Validations.
	// +optional
	PreRenderValidations []ValidationRule `json:"preRenderValidations,omitempty"`

	// PostRenderValidations are CEL-based rules evaluated after all traits are applied,
	// against the final rendered Kubernetes resources.
	// +optional
	PostRenderValidations []PostRenderValidation `json:"postRenderValidations,omitempty"`

	// Creates defines new Kubernetes resources to create when this trait is applied
	// +optional
	Creates []TraitCreate `json:"creates,omitempty"`

	// Patches defines modifications to existing resources generated by the ComponentType
	// +optional
	Patches []TraitPatch `json:"patches,omitempty"`

	// Removes deletes whole resources previously produced by the ComponentType or earlier traits.
	// Workload resources (e.g. Deployment, StatefulSet, CronJob) cannot be removed.
	// +optional
	Removes []TraitRemove `json:"removes,omitempty"`
}

// ClusterTraitStatus defines the observed state of ClusterTrait.
type ClusterTraitStatus struct {
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=ctrait;ctraits
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// ClusterTrait is the Schema for the clustertraits API.
// ClusterTrait is a cluster-scoped version of Trait that can be
// referenced by Components across all namespaces.
type ClusterTrait struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClusterTraitSpec   `json:"spec,omitempty"`
	Status ClusterTraitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterTraitList contains a list of ClusterTrait.
type ClusterTraitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterTrait `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ClusterTrait{}, &ClusterTraitList{})
}
