// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime" //nolint:staticcheck // runtime is used by TraitCreate, TraitPatch, JSONPatchOperation
)

// TraitSpec defines the desired state of Trait.
// +kubebuilder:validation:XValidation:rule="!(has(self.validations) && size(self.validations) > 0 && has(self.preRenderValidations) && size(self.preRenderValidations) > 0)",message="set only one of spec.validations or spec.preRenderValidations; validations is deprecated, use preRenderValidations"
type TraitSpec struct {
	// Parameters defines developer-facing configuration options for this trait.
	// +optional
	Parameters *SchemaSection `json:"parameters,omitempty"`

	// EnvironmentConfigs defines per-environment configurations for this trait via ReleaseBinding.
	// +optional
	EnvironmentConfigs *SchemaSection `json:"environmentConfigs,omitempty"`

	// Validations are CEL-based rules evaluated before rendering.
	//
	// Deprecated: use PreRenderValidations. Retained for backward compatibility;
	// it is mutually exclusive with PreRenderValidations and has identical semantics.
	// +optional
	Validations []ValidationRule `json:"validations,omitempty"`

	// PreRenderValidations are CEL-based rules evaluated before rendering, against
	// the trait's static parameters/environmentConfigs/metadata context.
	// All rules must evaluate to true for rendering to proceed. Replaces Validations.
	// +optional
	PreRenderValidations []ValidationRule `json:"preRenderValidations,omitempty"`

	// PostRenderValidations are CEL-based rules evaluated after all traits are applied,
	// against the final rendered Kubernetes resources.
	// +optional
	PostRenderValidations []PostRenderValidation `json:"postRenderValidations,omitempty"`

	// Creates defines new Kubernetes resources to create when this trait is applied
	// +optional
	Creates []TraitCreate `json:"creates,omitempty"`

	// Patches defines modifications to existing resources generated by the ComponentType
	// +optional
	Patches []TraitPatch `json:"patches,omitempty"`

	// Removes deletes whole resources previously produced by the ComponentType or earlier traits.
	// Workload resources (e.g. Deployment, StatefulSet, CronJob) cannot be removed.
	// +optional
	Removes []TraitRemove `json:"removes,omitempty"`
}

// EffectivePreRenderValidations returns the pre-render validation rules to apply.
// PreRenderValidations takes precedence; Validations is the deprecated fallback.
// The two are mutually exclusive (enforced by a CRD XValidation rule), so at most
// one is non-empty in practice.
func (s *TraitSpec) EffectivePreRenderValidations() []ValidationRule {
	if len(s.PreRenderValidations) > 0 {
		return s.PreRenderValidations
	}
	return s.Validations
}

// PostRenderValidation asserts a CEL rule against the rendered Kubernetes resources
// after all traits have been applied. It selects target resources by GVK (and an
// optional where filter), binds each match to the `resource` variable, and requires
// the rule to evaluate to true.
// +kubebuilder:validation:XValidation:rule="!has(self.forEach) || has(self.var)",message="var is required when forEach is specified"
type PostRenderValidation struct {
	// When is an optional CEL guard evaluated once against the trait context (the loop
	// variable is NOT in scope here). If set and it evaluates to false, this validation
	// is skipped entirely.
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	When string `json:"when,omitempty"`

	// ForEach repeats this validation for every item in a CEL-evaluated list, evaluated
	// against the trait context. Requires var. The loop variable is available in
	// target.where and rule, and mustMatch is applied per iteration.
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	ForEach string `json:"forEach,omitempty"`

	// Var names the binding for forEach iterations. Required when forEach is specified.
	// +optional
	// +kubebuilder:validation:Pattern=`^[a-zA-Z_][a-zA-Z0-9_]*$`
	Var string `json:"var,omitempty"`

	// Target selects which rendered resources this validation applies to.
	// +kubebuilder:validation:Required
	Target PostRenderTarget `json:"target"`

	// TargetPlane scopes selection to resources in a single plane, matching how trait
	// creates/patches/removes target a plane. Defaults to "dataplane".
	// +optional
	// +kubebuilder:validation:Enum=dataplane;observabilityplane
	// +kubebuilder:default=dataplane
	TargetPlane string `json:"targetPlane,omitempty"`

	// Rule is a CEL expression wrapped in ${...} evaluated with `resource` bound to each
	// matched resource (and the forEach loop variable, if any). It must evaluate to true.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	Rule string `json:"rule"`

	// Message is the error message shown when the rule evaluates to false.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Message string `json:"message"`
}

// TargetPlaneOrDefault returns the effective targetPlane, defaulting to "dataplane" when
// unset. The CRD default handles serialized objects; this covers structs built in-memory
// (tests), mirroring MustMatchOrDefault and the create/patch targetPlane normalization.
func (v *PostRenderValidation) TargetPlaneOrDefault() string {
	if v.TargetPlane == "" {
		return TargetPlaneDataPlane
	}
	return v.TargetPlane
}

// PostRenderTarget selects rendered resources by GVK with an optional where filter.
// It reuses the same GVK + where model as trait patches (PatchTarget) and adds
// MustMatch to require the selection to be non-empty.
type PostRenderTarget struct {
	PatchTarget `json:",inline"`

	// MustMatch requires at least one rendered resource to match this target.
	// When true (the default) and no resource matches, the validation fails.
	// This catches the case where an earlier/later trait removed the target resource.
	// +optional
	// +kubebuilder:default=true
	MustMatch *bool `json:"mustMatch,omitempty"`
}

// MustMatchOrDefault returns the effective MustMatch value, defaulting to true when unset.
// The CRD default handles serialized objects; this covers structs built in-memory (tests).
func (t *PostRenderTarget) MustMatchOrDefault() bool {
	return t.MustMatch == nil || *t.MustMatch
}

// TraitCreate defines a resource template to be created by the trait
// +kubebuilder:validation:XValidation:rule="!has(self.forEach) || has(self.var)",message="var is required when forEach is specified"
type TraitCreate struct {
	// TargetPlane specifies which plane this resource should be deployed to
	// Defaults to "dataplane" if not specified
	// +optional
	// +kubebuilder:validation:Enum=dataplane;observabilityplane
	// +kubebuilder:default=dataplane
	TargetPlane string `json:"targetPlane,omitempty"`

	// IncludeWhen is a CEL expression that determines if this resource should be created
	// If not specified, the resource is always created
	// Example: "${parameters.enableMetrics}"
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	IncludeWhen string `json:"includeWhen,omitempty"`

	// ForEach enables generating multiple resources from a list using CEL expression
	// Example: "${parameters.volumes}" to iterate over a list
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	ForEach string `json:"forEach,omitempty"`

	// Var is the loop variable name when using forEach
	// Example: "volume" will make each item available as ${volume} in templates
	// +optional
	// +kubebuilder:validation:Pattern=`^[a-zA-Z_][a-zA-Z0-9_]*$`
	Var string `json:"var,omitempty"`

	// Template contains the Kubernetes resource with CEL expressions
	// CEL expressions are enclosed in ${...} and will be evaluated at runtime
	// +kubebuilder:validation:Required
	// +kubebuilder:pruning:PreserveUnknownFields
	Template *runtime.RawExtension `json:"template"`
}

// TraitPatch defines a modification to an existing resource
// +kubebuilder:validation:XValidation:rule="!has(self.forEach) || has(self.var)",message="var is required when forEach is specified"
type TraitPatch struct {
	// ForEach repeats this patch for every item in a CEL-evaluated list
	// Requires 'var' to be set to name the binding used in operations
	// Example: forEach: ${spec.mounts}
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	ForEach string `json:"forEach,omitempty"`

	// Var names the binding for forEach iterations
	// Required when forEach is specified
	// Example: var: mount
	// +optional
	// +kubebuilder:validation:Pattern=`^[a-zA-Z_][a-zA-Z0-9_]*$`
	Var string `json:"var,omitempty"`

	// Target specifies which resource to patch
	// +kubebuilder:validation:Required
	Target PatchTarget `json:"target"`

	// TargetPlane specifies which plane's resources this patch targets
	// Defaults to "dataplane" if not specified
	// +optional
	// +kubebuilder:validation:Enum=dataplane;observabilityplane
	// +kubebuilder:default=dataplane
	TargetPlane string `json:"targetPlane,omitempty"`

	// Operations is the list of JSONPatch operations to apply to the target resource
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	Operations []JSONPatchOperation `json:"operations"`
}

// TraitRemove deletes whole resources previously produced by the ComponentType or earlier traits.
// Unlike TraitPatch, it removes the matched resources entirely instead of modifying them.
// Workload resource kinds (e.g. Deployment, StatefulSet, CronJob) are rejected by the webhook.
// +kubebuilder:validation:XValidation:rule="!has(self.forEach) || has(self.var)",message="var is required when forEach is specified"
type TraitRemove struct {
	// ForEach repeats this remove for every item in a CEL-evaluated list
	// Requires 'var' to be set to name the binding used in the where clause
	// Example: forEach: ${parameters.routesToDrop}
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	ForEach string `json:"forEach,omitempty"`

	// Var names the binding for forEach iterations
	// Required when forEach is specified
	// +optional
	// +kubebuilder:validation:Pattern=`^[a-zA-Z_][a-zA-Z0-9_]*$`
	Var string `json:"var,omitempty"`

	// Target specifies which resource to remove. Matching resources are deleted entirely.
	// +kubebuilder:validation:Required
	Target PatchTarget `json:"target"`

	// TargetPlane specifies which plane's resources this remove targets
	// Defaults to "dataplane" if not specified
	// +optional
	// +kubebuilder:validation:Enum=dataplane;observabilityplane
	// +kubebuilder:default=dataplane
	TargetPlane string `json:"targetPlane,omitempty"`
}

// PatchTarget specifies which resource to modify
type PatchTarget struct {
	// Group is the API group of the resource (e.g., "apps", "batch")
	// Must be explicitly set. Use empty string "" for core API resources (v1 Service, ConfigMap, etc.)
	// +kubebuilder:validation:Required
	Group string `json:"group"`

	// Version is the API version of the resource (e.g., "v1", "v1beta1")
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Version string `json:"version"`

	// Kind is the resource type to patch (e.g., "Deployment", "StatefulSet")
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Kind string `json:"kind"`

	// Where is an optional CEL expression to filter which resources to patch
	// Example: ${resource.metadata.name.endsWith("-secret-envs")}
	// +optional
	// +kubebuilder:validation:Pattern=`^\$\{[\s\S]+\}\s*$`
	Where string `json:"where,omitempty"`
}

// JSONPatchOperation defines a JSONPatch operation
// Supports standard operations (add, replace, remove) for map overlays
type JSONPatchOperation struct {
	// Op is the operation type
	// Standard operations: add, replace, remove (RFC 6902)
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Enum=add;replace;remove
	Op string `json:"op"`

	// Path is the JSON Pointer to the field to modify (RFC 6901)
	// Supports array filters: /spec/containers/[?(@.name=='app')]/volumeMounts/-
	// +kubebuilder:validation:Required
	Path string `json:"path"`

	// Value is the value to set (for add/replace operations)
	// Not used for remove operations
	// Can be a literal value, a structure with embedded CEL expressions,
	// or a standalone CEL expression.
	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Schemaless
	Value *runtime.RawExtension `json:"value,omitempty"`
}

// TraitStatus defines the observed state of Trait.
type TraitStatus struct {
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=trait;traits
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// Trait is the Schema for the traits API.
type Trait struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TraitSpec   `json:"spec,omitempty"`
	Status TraitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TraitList contains a list of Trait.
type TraitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Trait `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Trait{}, &TraitList{})
}
