// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateClusterProjectType provides a mock function with given fields: ctx, cpt
func (_m *MockService) CreateClusterProjectType(ctx context.Context, cpt *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error) {
	ret := _m.Called(ctx, cpt)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterProjectType")
	}

	var r0 *v1alpha1.ClusterProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error)); ok {
		return rf(ctx, cpt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterProjectType) *v1alpha1.ClusterProjectType); ok {
		r0 = rf(ctx, cpt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterProjectType) error); ok {
		r1 = rf(ctx, cpt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateClusterProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterProjectType'
type MockService_CreateClusterProjectType_Call struct {
	*mock.Call
}

// CreateClusterProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - cpt *v1alpha1.ClusterProjectType
func (_e *MockService_Expecter) CreateClusterProjectType(ctx interface{}, cpt interface{}) *MockService_CreateClusterProjectType_Call {
	return &MockService_CreateClusterProjectType_Call{Call: _e.mock.On("CreateClusterProjectType", ctx, cpt)}
}

func (_c *MockService_CreateClusterProjectType_Call) Run(run func(ctx context.Context, cpt *v1alpha1.ClusterProjectType)) *MockService_CreateClusterProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterProjectType))
	})
	return _c
}

func (_c *MockService_CreateClusterProjectType_Call) Return(_a0 *v1alpha1.ClusterProjectType, _a1 error) *MockService_CreateClusterProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateClusterProjectType_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error)) *MockService_CreateClusterProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClusterProjectType provides a mock function with given fields: ctx, cptName
func (_m *MockService) DeleteClusterProjectType(ctx context.Context, cptName string) error {
	ret := _m.Called(ctx, cptName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterProjectType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cptName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteClusterProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterProjectType'
type MockService_DeleteClusterProjectType_Call struct {
	*mock.Call
}

// DeleteClusterProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - cptName string
func (_e *MockService_Expecter) DeleteClusterProjectType(ctx interface{}, cptName interface{}) *MockService_DeleteClusterProjectType_Call {
	return &MockService_DeleteClusterProjectType_Call{Call: _e.mock.On("DeleteClusterProjectType", ctx, cptName)}
}

func (_c *MockService_DeleteClusterProjectType_Call) Run(run func(ctx context.Context, cptName string)) *MockService_DeleteClusterProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteClusterProjectType_Call) Return(_a0 error) *MockService_DeleteClusterProjectType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteClusterProjectType_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteClusterProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterProjectType provides a mock function with given fields: ctx, cptName
func (_m *MockService) GetClusterProjectType(ctx context.Context, cptName string) (*v1alpha1.ClusterProjectType, error) {
	ret := _m.Called(ctx, cptName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterProjectType")
	}

	var r0 *v1alpha1.ClusterProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.ClusterProjectType, error)); ok {
		return rf(ctx, cptName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.ClusterProjectType); ok {
		r0 = rf(ctx, cptName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cptName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetClusterProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterProjectType'
type MockService_GetClusterProjectType_Call struct {
	*mock.Call
}

// GetClusterProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - cptName string
func (_e *MockService_Expecter) GetClusterProjectType(ctx interface{}, cptName interface{}) *MockService_GetClusterProjectType_Call {
	return &MockService_GetClusterProjectType_Call{Call: _e.mock.On("GetClusterProjectType", ctx, cptName)}
}

func (_c *MockService_GetClusterProjectType_Call) Run(run func(ctx context.Context, cptName string)) *MockService_GetClusterProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetClusterProjectType_Call) Return(_a0 *v1alpha1.ClusterProjectType, _a1 error) *MockService_GetClusterProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetClusterProjectType_Call) RunAndReturn(run func(context.Context, string) (*v1alpha1.ClusterProjectType, error)) *MockService_GetClusterProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterProjectTypeSchema provides a mock function with given fields: ctx, cptName
func (_m *MockService) GetClusterProjectTypeSchema(ctx context.Context, cptName string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, cptName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterProjectTypeSchema")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, cptName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, cptName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cptName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetClusterProjectTypeSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterProjectTypeSchema'
type MockService_GetClusterProjectTypeSchema_Call struct {
	*mock.Call
}

// GetClusterProjectTypeSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - cptName string
func (_e *MockService_Expecter) GetClusterProjectTypeSchema(ctx interface{}, cptName interface{}) *MockService_GetClusterProjectTypeSchema_Call {
	return &MockService_GetClusterProjectTypeSchema_Call{Call: _e.mock.On("GetClusterProjectTypeSchema", ctx, cptName)}
}

func (_c *MockService_GetClusterProjectTypeSchema_Call) Run(run func(ctx context.Context, cptName string)) *MockService_GetClusterProjectTypeSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetClusterProjectTypeSchema_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetClusterProjectTypeSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetClusterProjectTypeSchema_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockService_GetClusterProjectTypeSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterProjectTypes provides a mock function with given fields: ctx, opts
func (_m *MockService) ListClusterProjectTypes(ctx context.Context, opts services.ListOptions) (*services.ListResult[v1alpha1.ClusterProjectType], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterProjectTypes")
	}

	var r0 *services.ListResult[v1alpha1.ClusterProjectType]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterProjectType], error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) *services.ListResult[v1alpha1.ClusterProjectType]); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ClusterProjectType])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListClusterProjectTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterProjectTypes'
type MockService_ListClusterProjectTypes_Call struct {
	*mock.Call
}

// ListClusterProjectTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListClusterProjectTypes(ctx interface{}, opts interface{}) *MockService_ListClusterProjectTypes_Call {
	return &MockService_ListClusterProjectTypes_Call{Call: _e.mock.On("ListClusterProjectTypes", ctx, opts)}
}

func (_c *MockService_ListClusterProjectTypes_Call) Run(run func(ctx context.Context, opts services.ListOptions)) *MockService_ListClusterProjectTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListClusterProjectTypes_Call) Return(_a0 *services.ListResult[v1alpha1.ClusterProjectType], _a1 error) *MockService_ListClusterProjectTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListClusterProjectTypes_Call) RunAndReturn(run func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterProjectType], error)) *MockService_ListClusterProjectTypes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterProjectType provides a mock function with given fields: ctx, cpt
func (_m *MockService) UpdateClusterProjectType(ctx context.Context, cpt *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error) {
	ret := _m.Called(ctx, cpt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterProjectType")
	}

	var r0 *v1alpha1.ClusterProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error)); ok {
		return rf(ctx, cpt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterProjectType) *v1alpha1.ClusterProjectType); ok {
		r0 = rf(ctx, cpt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterProjectType) error); ok {
		r1 = rf(ctx, cpt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateClusterProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterProjectType'
type MockService_UpdateClusterProjectType_Call struct {
	*mock.Call
}

// UpdateClusterProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - cpt *v1alpha1.ClusterProjectType
func (_e *MockService_Expecter) UpdateClusterProjectType(ctx interface{}, cpt interface{}) *MockService_UpdateClusterProjectType_Call {
	return &MockService_UpdateClusterProjectType_Call{Call: _e.mock.On("UpdateClusterProjectType", ctx, cpt)}
}

func (_c *MockService_UpdateClusterProjectType_Call) Run(run func(ctx context.Context, cpt *v1alpha1.ClusterProjectType)) *MockService_UpdateClusterProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterProjectType))
	})
	return _c
}

func (_c *MockService_UpdateClusterProjectType_Call) Return(_a0 *v1alpha1.ClusterProjectType, _a1 error) *MockService_UpdateClusterProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateClusterProjectType_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterProjectType) (*v1alpha1.ClusterProjectType, error)) *MockService_UpdateClusterProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
