//go:build go1.22

// Package internalgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package internalgen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/openchoreo/openchoreo/internal/observer/api/gen"
)

// Defines values for AlertRuleRequestConditionOperator.
const (
	AlertRuleRequestConditionOperatorEq  AlertRuleRequestConditionOperator = "eq"
	AlertRuleRequestConditionOperatorGt  AlertRuleRequestConditionOperator = "gt"
	AlertRuleRequestConditionOperatorGte AlertRuleRequestConditionOperator = "gte"
	AlertRuleRequestConditionOperatorLt  AlertRuleRequestConditionOperator = "lt"
	AlertRuleRequestConditionOperatorLte AlertRuleRequestConditionOperator = "lte"
	AlertRuleRequestConditionOperatorNeq AlertRuleRequestConditionOperator = "neq"
)

// Defines values for AlertRuleRequestSourceMetric.
const (
	AlertRuleRequestSourceMetricBudget      AlertRuleRequestSourceMetric = "budget"
	AlertRuleRequestSourceMetricCpuUsage    AlertRuleRequestSourceMetric = "cpu_usage"
	AlertRuleRequestSourceMetricMemoryUsage AlertRuleRequestSourceMetric = "memory_usage"
)

// Defines values for AlertRuleRequestSourceType.
const (
	AlertRuleRequestSourceTypeBudget AlertRuleRequestSourceType = "budget"
	AlertRuleRequestSourceTypeLog    AlertRuleRequestSourceType = "log"
	AlertRuleRequestSourceTypeMetric AlertRuleRequestSourceType = "metric"
)

// Defines values for AlertRuleResponseConditionOperator.
const (
	AlertRuleResponseConditionOperatorEq  AlertRuleResponseConditionOperator = "eq"
	AlertRuleResponseConditionOperatorGt  AlertRuleResponseConditionOperator = "gt"
	AlertRuleResponseConditionOperatorGte AlertRuleResponseConditionOperator = "gte"
	AlertRuleResponseConditionOperatorLt  AlertRuleResponseConditionOperator = "lt"
	AlertRuleResponseConditionOperatorLte AlertRuleResponseConditionOperator = "lte"
	AlertRuleResponseConditionOperatorNeq AlertRuleResponseConditionOperator = "neq"
)

// Defines values for AlertRuleResponseSourceMetric.
const (
	AlertRuleResponseSourceMetricBudget      AlertRuleResponseSourceMetric = "budget"
	AlertRuleResponseSourceMetricCpuUsage    AlertRuleResponseSourceMetric = "cpu_usage"
	AlertRuleResponseSourceMetricMemoryUsage AlertRuleResponseSourceMetric = "memory_usage"
)

// Defines values for AlertRuleResponseSourceType.
const (
	AlertRuleResponseSourceTypeBudget AlertRuleResponseSourceType = "budget"
	AlertRuleResponseSourceTypeLog    AlertRuleResponseSourceType = "log"
	AlertRuleResponseSourceTypeMetric AlertRuleResponseSourceType = "metric"
)

// Defines values for AlertWebhookResponseStatus.
const (
	AlertWebhookResponseStatusError   AlertWebhookResponseStatus = "error"
	AlertWebhookResponseStatusSuccess AlertWebhookResponseStatus = "success"
)

// Defines values for AlertingRuleSyncResponseAction.
const (
	AlertingRuleSyncResponseActionCreated   AlertingRuleSyncResponseAction = "created"
	AlertingRuleSyncResponseActionDeleted   AlertingRuleSyncResponseAction = "deleted"
	AlertingRuleSyncResponseActionUnchanged AlertingRuleSyncResponseAction = "unchanged"
	AlertingRuleSyncResponseActionUpdated   AlertingRuleSyncResponseAction = "updated"
)

// Defines values for AlertingRuleSyncResponseStatus.
const (
	AlertingRuleSyncResponseStatusFailed AlertingRuleSyncResponseStatus = "failed"
	AlertingRuleSyncResponseStatusSynced AlertingRuleSyncResponseStatus = "synced"
)

// AlertRuleRequest defines model for AlertRuleRequest.
type AlertRuleRequest struct {
	Condition struct {
		// Enabled Whether the alert rule is enabled
		Enabled bool `json:"enabled"`

		// Interval The interval of time to query for the alert rule
		Interval string `json:"interval"`

		// Operator The operator to use for the alert rule
		Operator AlertRuleRequestConditionOperator `json:"operator"`

		// Threshold The threshold value to use for the alert rule
		Threshold float32 `json:"threshold"`

		// Window The window of time to query for the alert rule
		Window string `json:"window"`
	} `json:"condition"`
	Metadata struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid openapi_types.UUID `json:"componentUid"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid openapi_types.UUID `json:"environmentUid"`

		// Name The name of the alert rule
		Name string `json:"name"`

		// Namespace The namespace of the alert rule CR
		Namespace string `json:"namespace"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid openapi_types.UUID `json:"projectUid"`
	} `json:"metadata"`
	Source struct {
		// Metric The metric to query for metric based alerts
		Metric *AlertRuleRequestSourceMetric `json:"metric,omitempty"`

		// Query The query to execute for log based alerts
		Query *string `json:"query,omitempty"`

		// Type The type of the source
		Type AlertRuleRequestSourceType `json:"type"`
	} `json:"source"`
}

// AlertRuleRequestConditionOperator The operator to use for the alert rule
type AlertRuleRequestConditionOperator string

// AlertRuleRequestSourceMetric The metric to query for metric based alerts
type AlertRuleRequestSourceMetric string

// AlertRuleRequestSourceType The type of the source
type AlertRuleRequestSourceType string

// AlertRuleResponse defines model for AlertRuleResponse.
type AlertRuleResponse struct {
	Condition *struct {
		// Enabled Whether the alert rule is enabled
		Enabled *bool `json:"enabled,omitempty"`

		// Interval The interval of time to query for the alert rule
		Interval *string `json:"interval,omitempty"`

		// Operator The operator to use for the alert rule
		Operator *AlertRuleResponseConditionOperator `json:"operator,omitempty"`

		// Threshold The threshold value to use for the alert rule
		Threshold *float32 `json:"threshold,omitempty"`

		// Window The window of time to query for the alert rule
		Window *string `json:"window,omitempty"`
	} `json:"condition,omitempty"`
	Metadata *struct {
		// ComponentUid The OpenChoreo component UID to query
		ComponentUid *openapi_types.UUID `json:"componentUid,omitempty"`

		// EnvironmentUid The OpenChoreo environment UID to query
		EnvironmentUid *openapi_types.UUID `json:"environmentUid,omitempty"`

		// Name The name of the alert rule
		Name *string `json:"name,omitempty"`

		// Namespace The namespace of the alert rule CR
		Namespace *string `json:"namespace,omitempty"`

		// ProjectUid The OpenChoreo project UID to query
		ProjectUid *openapi_types.UUID `json:"projectUid,omitempty"`
	} `json:"metadata,omitempty"`
	Source *struct {
		// Metric The metric to query for metric based alerts
		Metric *AlertRuleResponseSourceMetric `json:"metric,omitempty"`

		// Query The query to execute for log based alerts
		Query *string `json:"query,omitempty"`

		// Type The type of the source
		Type *AlertRuleResponseSourceType `json:"type,omitempty"`
	} `json:"source,omitempty"`
}

// AlertRuleResponseConditionOperator The operator to use for the alert rule
type AlertRuleResponseConditionOperator string

// AlertRuleResponseSourceMetric The metric to query for metric based alerts
type AlertRuleResponseSourceMetric string

// AlertRuleResponseSourceType The type of the source
type AlertRuleResponseSourceType string

// AlertWebhookRequest defines model for AlertWebhookRequest.
type AlertWebhookRequest struct {
	// AlertTimestamp The timestamp of the alert
	AlertTimestamp *time.Time `json:"alertTimestamp,omitempty"`

	// AlertValue The value of the alert
	AlertValue *float32 `json:"alertValue,omitempty"`

	// RuleName The name of the alert rule
	RuleName *string `json:"ruleName,omitempty"`

	// RuleNamespace The namespace of the alert rule
	RuleNamespace *string `json:"ruleNamespace,omitempty"`
}

// AlertWebhookResponse defines model for AlertWebhookResponse.
type AlertWebhookResponse struct {
	// Message The message of the alert webhook
	Message *string `json:"message,omitempty"`

	// Status The status of the alert webhook
	Status *AlertWebhookResponseStatus `json:"status,omitempty"`
}

// AlertWebhookResponseStatus The status of the alert webhook
type AlertWebhookResponseStatus string

// AlertingRuleSyncResponse defines model for AlertingRuleSyncResponse.
type AlertingRuleSyncResponse struct {
	// Action The action taken on the alert rule
	Action *AlertingRuleSyncResponseAction `json:"action,omitempty"`

	// LastSyncedAt The timestamp of the last sync
	LastSyncedAt *string `json:"lastSyncedAt,omitempty"`

	// RuleBackendId The backend ID (UID from observability backend) of the alert rule
	RuleBackendId *string `json:"ruleBackendId,omitempty"`

	// RuleLogicalId The logical ID (name) of the alert rule
	RuleLogicalId *string `json:"ruleLogicalId,omitempty"`

	// Status The status of the alert rule
	Status *AlertingRuleSyncResponseStatus `json:"status,omitempty"`
}

// AlertingRuleSyncResponseAction The action taken on the alert rule
type AlertingRuleSyncResponseAction string

// AlertingRuleSyncResponseStatus The status of the alert rule
type AlertingRuleSyncResponseStatus string

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = AlertRuleRequest

// UpdateAlertRuleJSONRequestBody defines body for UpdateAlertRule for application/json ContentType.
type UpdateAlertRuleJSONRequestBody = AlertRuleRequest

// HandleAlertWebhookJSONRequestBody defines body for HandleAlertWebhook for application/json ContentType.
type HandleAlertWebhookJSONRequestBody = AlertWebhookRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) CreateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlertRule(w, r, sourceType)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlertRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlertRule operation middleware
func (siw *ServerInterfaceWrapper) GetAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAlertRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateAlertRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sourceType" -------------
	var sourceType string

	err = runtime.BindStyledParameterWithOptions("simple", "sourceType", r.PathValue("sourceType"), &sourceType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sourceType", Err: err})
		return
	}

	// ------------- Path parameter "ruleName" -------------
	var ruleName string

	err = runtime.BindStyledParameterWithOptions("simple", "ruleName", r.PathValue("ruleName"), &ruleName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ruleName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAlertRule(w, r, sourceType, ruleName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleAlertWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleAlertWebhook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules", wrapper.CreateAlertRule)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.DeleteAlertRule)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.GetAlertRule)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName}", wrapper.UpdateAlertRule)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1alpha1/alerts/webhook", wrapper.HandleAlertWebhook)

	return m
}

type CreateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	Body       *CreateAlertRuleJSONRequestBody
}

type CreateAlertRuleResponseObject interface {
	VisitCreateAlertRuleResponse(w http.ResponseWriter) error
}

type CreateAlertRule201JSONResponse AlertingRuleSyncResponse

func (response CreateAlertRule201JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule400JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule409JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule409JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response CreateAlertRule500JSONResponse) VisitCreateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type DeleteAlertRuleResponseObject interface {
	VisitDeleteAlertRuleResponse(w http.ResponseWriter) error
}

type DeleteAlertRule200JSONResponse AlertingRuleSyncResponse

func (response DeleteAlertRule200JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule400JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule400JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule404JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule404JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteAlertRule500JSONResponse externalRef0.ErrorResponse

func (response DeleteAlertRule500JSONResponse) VisitDeleteAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
}

type GetAlertRuleResponseObject interface {
	VisitGetAlertRuleResponse(w http.ResponseWriter) error
}

type GetAlertRule200JSONResponse AlertRuleResponse

func (response GetAlertRule200JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule400JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule400JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule404JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule404JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetAlertRule500JSONResponse externalRef0.ErrorResponse

func (response GetAlertRule500JSONResponse) VisitGetAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRuleRequestObject struct {
	SourceType string `json:"sourceType"`
	RuleName   string `json:"ruleName"`
	Body       *UpdateAlertRuleJSONRequestBody
}

type UpdateAlertRuleResponseObject interface {
	VisitUpdateAlertRuleResponse(w http.ResponseWriter) error
}

type UpdateAlertRule200JSONResponse AlertingRuleSyncResponse

func (response UpdateAlertRule200JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule400JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule400JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule404JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule404JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateAlertRule500JSONResponse externalRef0.ErrorResponse

func (response UpdateAlertRule500JSONResponse) VisitUpdateAlertRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhookRequestObject struct {
	Body *HandleAlertWebhookJSONRequestBody
}

type HandleAlertWebhookResponseObject interface {
	VisitHandleAlertWebhookResponse(w http.ResponseWriter) error
}

type HandleAlertWebhook200JSONResponse AlertWebhookResponse

func (response HandleAlertWebhook200JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook400JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook400JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleAlertWebhook500JSONResponse externalRef0.ErrorResponse

func (response HandleAlertWebhook500JSONResponse) VisitHandleAlertWebhookResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create alert rule
	// (POST /api/v1alpha1/alerts/sources/{sourceType}/rules)
	CreateAlertRule(ctx context.Context, request CreateAlertRuleRequestObject) (CreateAlertRuleResponseObject, error)
	// Delete alert rule
	// (DELETE /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	DeleteAlertRule(ctx context.Context, request DeleteAlertRuleRequestObject) (DeleteAlertRuleResponseObject, error)
	// Get alert rule
	// (GET /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	GetAlertRule(ctx context.Context, request GetAlertRuleRequestObject) (GetAlertRuleResponseObject, error)
	// Update alert rule
	// (PUT /api/v1alpha1/alerts/sources/{sourceType}/rules/{ruleName})
	UpdateAlertRule(ctx context.Context, request UpdateAlertRuleRequestObject) (UpdateAlertRuleResponseObject, error)
	// Handles triggered alerts from the alerting backend
	// (POST /api/v1alpha1/alerts/webhook)
	HandleAlertWebhook(ctx context.Context, request HandleAlertWebhookRequestObject) (HandleAlertWebhookResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateAlertRule operation middleware
func (sh *strictHandler) CreateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string) {
	var request CreateAlertRuleRequestObject

	request.SourceType = sourceType

	var body CreateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAlertRule(ctx, request.(CreateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAlertRuleResponseObject); ok {
		if err := validResponse.VisitCreateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteAlertRule operation middleware
func (sh *strictHandler) DeleteAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request DeleteAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteAlertRule(ctx, request.(DeleteAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteAlertRuleResponseObject); ok {
		if err := validResponse.VisitDeleteAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAlertRule operation middleware
func (sh *strictHandler) GetAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request GetAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAlertRule(ctx, request.(GetAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAlertRuleResponseObject); ok {
		if err := validResponse.VisitGetAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateAlertRule operation middleware
func (sh *strictHandler) UpdateAlertRule(w http.ResponseWriter, r *http.Request, sourceType string, ruleName string) {
	var request UpdateAlertRuleRequestObject

	request.SourceType = sourceType
	request.RuleName = ruleName

	var body UpdateAlertRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateAlertRule(ctx, request.(UpdateAlertRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateAlertRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateAlertRuleResponseObject); ok {
		if err := validResponse.VisitUpdateAlertRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleAlertWebhook operation middleware
func (sh *strictHandler) HandleAlertWebhook(w http.ResponseWriter, r *http.Request) {
	var request HandleAlertWebhookRequestObject

	var body HandleAlertWebhookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleAlertWebhook(ctx, request.(HandleAlertWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleAlertWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleAlertWebhookResponseObject); ok {
		if err := validResponse.VisitHandleAlertWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW0/kOBb+K5Z3JUBKXWBmpdl6o+nemZJYaAE989C0Wq74VOJpxw6+QNei+u+rYydV",
	"SVVSDahnQb28QMp2zvU7F5/c01QXpVagnKWTe2rTHAoWHo8lGHfhJVzAjQfrcK00ugTjBIQTqVZcOKHV",
	"9hYoNpPA8ZGDTY0o4zn6Rw4uB0NcDoQhB2K8BCIsqV9JqFuUQCd0prUEpugyoUI5MLdMbtO7yoHUu0TP",
	"iRMFEKfJjQezIHO9yWlN3jojVIbUUXDmtOmmXu8iVW+hmyYoX9DJR5o5mtDM4ZJ04U/YvaEJVXBDP3Vw",
	"d7kBm2vJu9mvtsktkx52SlHRVr6YgUHad0JxfddNOO49zWbLhBq48cKgiz/Stesqhg2PNczb1HVtCT37",
	"E1KH0hbgGGeOdSGtAukH0WOm8xLUSa4NaLI6TD5M3670ogmda1MwRyfUe8G7gADqVhitigcyahx/NCvF",
	"CuhmgDvBK9/ELZ60JUt3EArb29TIyUUXwdJo9MVDdK+OPlLvDdwEIzT1aImw5Y+kjYMuCFntTbRHG0AF",
	"OCPSbq3iXjsAqrUZs8Cj3WwjytPSf/aWZShwAYU2i9XPmecZuM5AjzbqFCEydprAV0i9i+EtdbYpwHby",
	"CAudeWNRrhxfWWWtgNRZED0YZYfQG/4Ku9tm3zi1CuOVO5JGqejyWqPU2FIrC6+15rXWNDD4Win+HyvF",
	"a3L/y5P7diLvzs1/wCzX+kvvTSDocCUKsI4VZY/M9XYLZE0kcOZggMe6jBFO/45pqZt8zFgbpLeSFEL6",
	"7DsEVE3naUH1MLi3Ld9XGAuwAZ096A+bbQnuIskutaxjzttuWnGvj1QNPuvTFGyIJ2O0eRDsKlWFyrAH",
	"uFyotF9dltZNwLaEcY849gUUwYe+ypkaYC6Uf1/y+kmlOVNZeOYgAVe7Al0y61BE4MfugUDHV4hdqLQP",
	"SW9Y+gUUn/Yk01ncJtO3ZB+z6NzoguiZxUZkJqRwi/rIwcPRe6ozkTLZx1PG7cATkfxAyo8F0IZjbDAs",
	"5gQmZKcDutATTQFmwErx+R3Crh8/AZUnmvcETNgmqebQtDIYgv9ETLNfWVFKlOD8zeXg98PB6eDoqMsW",
	"vZH5my+YGhhgHLvQimd9usng38JaoTJSd9dkLkByS/asYzHf7hGmONkDxcOvzioinNypbYNz5YYZ43Wq",
	"x8Bg3uXaiP9Ez2gzE5yDwjZTu39pr+LNTM2lSF199VdMXgbLBX/Es1NUC3ugB3p2Gbrxua76f8fSEHGx",
	"IaKNFuMKWIGq7uxDzmtXTiv5yPH7KV4GwjKvE0bt8T1LakWuVamNI/vTs6t3F2fHp5/fn19cJYTDnHnp",
	"yC/jXw4Pgh/ga6ltICUXhFnCSCq9dWAGUqdI5yT+nL4nlxFPZH8F3prbwZBMHcp1dn5FjPYOODbm2mc5",
	"CnitMubgji0Cx/oYsDQPYIqo9c4KDkGfSoLhtbpWJ0xKMJYwgxeZQbW1boNtQpR2BHONt2Ds5FoRMmiY",
	"pU43pWQK9mxl02p1dYsj6CyjkRfZb7WSH94eRJJMbVAsNPcSSUqd2QHjrETJVs3aemm/VXkOUK1j73JQ",
	"TqQMPT8hLhc2OJdDKpkBS5QmFlJvkFMYcUJCZpAyvN0orfBOeK1AzbVJgQ/JGbg7bb7UZo0SChvtGXUb",
	"XmMASJFClWYqVB6XLM2BHA3HGDpG0gnNnSvtZDS6u7sbsrA91CYbVe/a0en05N3Z5bvB0XA8zF0hG0FL",
	"v4VfmtBbMDYC/nA4Ho6rS6ZipaAT+tNwPPyJJrRkLg/5b8RKMbo9ZLLM2eEo9p6j2ELa0X18uFqUsByh",
	"y8IrJTOsAAfG0snHzsQe3mo1pQ2v70udJZUbE/RobEgPQqagkyAara85dC0BbU4VnPGQVNPpeOd/ZK/7",
	"KaGlth0V+yT0AgjI5oignQsa2T/e0IVWWDirl1fAr0QG695ovqjTFqjAlpWlrCA6+tPGHmat0N8NzOmE",
	"/m20DsZRNYwfbU3il+2RCxonLMSiF5x2ND78vvy7urMgR9ucx2sjVl0WqVrCuZdygej8eTz+bqLtKP0d",
	"wk3VLZOCE1PbEYX55zMJ07AUk9gMLAh8FdZZFOsfz2ijKrvE8k1i/cZz1hcFw0vuKmZarSDLMD9EtSz9",
	"hG88MtmM7utr1TLGKXbh2xH7Nqw/MWLjy+2IbYXN+LnDprp8vPSw+fn5wwZ7lXnoP198xNSY3RkxCcXi",
	"tYX3X8E9Eey/gvvfIb01v9/tOIP1Gm5fQf5jgTwA9RsI/yGayeRRw8MOwVZjyF1iFUKdgspcTieH3Q2t",
	"78gWH8JE64kJI778MvvZZy/M1azwNWf9SDmrDpcntbL1+BsvyZ2Xy9+Y4hIscUZkGZjV1544plllCqGy",
	"eoK7FZKRRPNbwF8ZlRsfep4jMDe/ePRCrbI+yYOFXnhcvuwoeBJOt8NkuVq87xNiYxwYhpitiR4BxUst",
	"VPgkWg/VIoflp+V/AwAA//88eF/AsCgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./observer-api.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
