// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	k8sresources "github.com/openchoreo/openchoreo/internal/openchoreo-api/services/k8sresources"
	mock "github.com/stretchr/testify/mock"

	models "github.com/openchoreo/openchoreo/internal/openchoreo-api/models"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetResourceEvents provides a mock function with given fields: ctx, namespaceName, releaseBindingName, group, version, kind, name
func (_m *MockService) GetResourceEvents(ctx context.Context, namespaceName string, releaseBindingName string, group string, version string, kind string, name string) (*models.ResourceEventsResponse, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName, group, version, kind, name)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceEvents")
	}

	var r0 *models.ResourceEventsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (*models.ResourceEventsResponse, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName, group, version, kind, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) *models.ResourceEventsResponse); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName, group, version, kind, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourceEventsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName, group, version, kind, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResourceEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceEvents'
type MockService_GetResourceEvents_Call struct {
	*mock.Call
}

// GetResourceEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
//   - group string
//   - version string
//   - kind string
//   - name string
func (_e *MockService_Expecter) GetResourceEvents(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}, group interface{}, version interface{}, kind interface{}, name interface{}) *MockService_GetResourceEvents_Call {
	return &MockService_GetResourceEvents_Call{Call: _e.mock.On("GetResourceEvents", ctx, namespaceName, releaseBindingName, group, version, kind, name)}
}

func (_c *MockService_GetResourceEvents_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string, group string, version string, kind string, name string)) *MockService_GetResourceEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockService_GetResourceEvents_Call) Return(_a0 *models.ResourceEventsResponse, _a1 error) *MockService_GetResourceEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResourceEvents_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string) (*models.ResourceEventsResponse, error)) *MockService_GetResourceEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceLogs provides a mock function with given fields: ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds
func (_m *MockService) GetResourceLogs(ctx context.Context, namespaceName string, releaseBindingName string, podName string, container string, sinceSeconds *int64) (*models.ResourcePodLogsResponse, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceLogs")
	}

	var r0 *models.ResourcePodLogsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *int64) (*models.ResourcePodLogsResponse, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, *int64) *models.ResourcePodLogsResponse); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ResourcePodLogsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, *int64) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResourceLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceLogs'
type MockService_GetResourceLogs_Call struct {
	*mock.Call
}

// GetResourceLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
//   - podName string
//   - container string
//   - sinceSeconds *int64
func (_e *MockService_Expecter) GetResourceLogs(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}, podName interface{}, container interface{}, sinceSeconds interface{}) *MockService_GetResourceLogs_Call {
	return &MockService_GetResourceLogs_Call{Call: _e.mock.On("GetResourceLogs", ctx, namespaceName, releaseBindingName, podName, container, sinceSeconds)}
}

func (_c *MockService_GetResourceLogs_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string, podName string, container string, sinceSeconds *int64)) *MockService_GetResourceLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(*int64))
	})
	return _c
}

func (_c *MockService_GetResourceLogs_Call) Return(_a0 *models.ResourcePodLogsResponse, _a1 error) *MockService_GetResourceLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResourceLogs_Call) RunAndReturn(run func(context.Context, string, string, string, string, *int64) (*models.ResourcePodLogsResponse, error)) *MockService_GetResourceLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceTree provides a mock function with given fields: ctx, namespaceName, releaseBindingName
func (_m *MockService) GetResourceTree(ctx context.Context, namespaceName string, releaseBindingName string) (*k8sresources.K8sResourceTreeResult, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceTree")
	}

	var r0 *k8sresources.K8sResourceTreeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*k8sresources.K8sResourceTreeResult, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *k8sresources.K8sResourceTreeResult); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8sresources.K8sResourceTreeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResourceTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceTree'
type MockService_GetResourceTree_Call struct {
	*mock.Call
}

// GetResourceTree is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
func (_e *MockService_Expecter) GetResourceTree(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}) *MockService_GetResourceTree_Call {
	return &MockService_GetResourceTree_Call{Call: _e.mock.On("GetResourceTree", ctx, namespaceName, releaseBindingName)}
}

func (_c *MockService_GetResourceTree_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string)) *MockService_GetResourceTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetResourceTree_Call) Return(_a0 *k8sresources.K8sResourceTreeResult, _a1 error) *MockService_GetResourceTree_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResourceTree_Call) RunAndReturn(run func(context.Context, string, string) (*k8sresources.K8sResourceTreeResult, error)) *MockService_GetResourceTree_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerCronJob provides a mock function with given fields: ctx, namespaceName, releaseBindingName, overrides
func (_m *MockService) TriggerCronJob(ctx context.Context, namespaceName string, releaseBindingName string, overrides *models.CronJobTriggerRequest) (*models.CronJobTriggerResponse, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName, overrides)

	if len(ret) == 0 {
		panic("no return value specified for TriggerCronJob")
	}

	var r0 *models.CronJobTriggerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *models.CronJobTriggerRequest) (*models.CronJobTriggerResponse, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName, overrides)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *models.CronJobTriggerRequest) *models.CronJobTriggerResponse); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName, overrides)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CronJobTriggerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *models.CronJobTriggerRequest) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName, overrides)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_TriggerCronJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerCronJob'
type MockService_TriggerCronJob_Call struct {
	*mock.Call
}

// TriggerCronJob is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
//   - overrides *models.CronJobTriggerRequest
func (_e *MockService_Expecter) TriggerCronJob(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}, overrides interface{}) *MockService_TriggerCronJob_Call {
	return &MockService_TriggerCronJob_Call{Call: _e.mock.On("TriggerCronJob", ctx, namespaceName, releaseBindingName, overrides)}
}

func (_c *MockService_TriggerCronJob_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string, overrides *models.CronJobTriggerRequest)) *MockService_TriggerCronJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*models.CronJobTriggerRequest))
	})
	return _c
}

func (_c *MockService_TriggerCronJob_Call) Return(_a0 *models.CronJobTriggerResponse, _a1 error) *MockService_TriggerCronJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_TriggerCronJob_Call) RunAndReturn(run func(context.Context, string, string, *models.CronJobTriggerRequest) (*models.CronJobTriggerResponse, error)) *MockService_TriggerCronJob_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
