// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package project

import (
	"encoding/json"
	"errors"
	"io"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
	extv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

const testSchema = `{
  "type": "object",
  "properties": {
    "tier": {"type": "string", "description": "Service tier", "enum": ["gold", "silver"]},
    "replicas": {"type": "integer", "default": 3}
  },
  "required": ["tier"]
}`

func schemaFrom(t *testing.T, src string) *extv1.JSONSchemaProps {
	t.Helper()
	var s extv1.JSONSchemaProps
	require.NoError(t, json.Unmarshal([]byte(src), &s))
	return &s
}

func baseOpts() *Options {
	return &Options{
		ProjectName:               "online-store",
		Namespace:                 "acme",
		ProjectTypeKind:           "ProjectType",
		ProjectTypeName:           "web-service",
		DeploymentPipeline:        "default",
		IncludeAllFields:          true,
		IncludeFieldDescriptions:  true,
		IncludeStructuralComments: true,
	}
}

// countDocs decodes the multi-document YAML and returns how many documents parsed.
func countDocs(t *testing.T, out string) int {
	t.Helper()
	dec := yaml.NewDecoder(strings.NewReader(out))
	docs := 0
	for {
		var v any
		err := dec.Decode(&v)
		if errors.Is(err, io.EOF) {
			break
		}
		require.NoError(t, err, "document %d must be valid YAML", docs+1)
		docs++
	}
	return docs
}

func TestGenerate_ProjectOnly(t *testing.T) {
	g := NewGenerator(schemaFrom(t, testSchema), baseOpts())
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Equal(t, 1, countDocs(t, out))
	assert.Contains(t, out, "apiVersion: openchoreo.dev/v1alpha1")
	assert.Contains(t, out, "kind: Project")
	assert.Contains(t, out, "name: online-store")
	assert.Contains(t, out, "namespace: acme")
	assert.Contains(t, out, "deploymentPipelineRef:")
	assert.Contains(t, out, "kind: ProjectType")
	assert.Contains(t, out, "name: web-service")
	assert.NotContains(t, out, "kind: ProjectReleaseBinding")
}

func TestGenerate_RequiredAndDefaultedParameters(t *testing.T) {
	g := NewGenerator(schemaFrom(t, testSchema), baseOpts())
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Contains(t, out, "parameters:")
	// required field is active, with description + enum hint
	assert.Contains(t, out, "tier:")
	assert.Contains(t, out, "Service tier")
	// optional field with a default is commented out
	assert.Contains(t, out, "# replicas: 3")
}

func TestGenerate_SkipComments(t *testing.T) {
	opts := baseOpts()
	opts.IncludeFieldDescriptions = false
	opts.IncludeStructuralComments = false

	g := NewGenerator(schemaFrom(t, testSchema), opts)
	out, err := g.Generate()
	require.NoError(t, err)

	assert.NotContains(t, out, "Generated by occ project scaffold")
	assert.NotContains(t, out, "Project type is immutable")
	assert.NotContains(t, out, "Service tier")
	assert.Contains(t, out, "kind: Project")
}

func TestGenerate_BindingPerEnvironment(t *testing.T) {
	opts := baseOpts()
	opts.Environments = []string{"dev", "staging", "prod"}

	g := NewGenerator(schemaFrom(t, testSchema), opts)
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Equal(t, 4, countDocs(t, out), "Project + one binding per environment")
	assert.Contains(t, out, "name: online-store-dev")
	assert.Contains(t, out, "name: online-store-staging")
	assert.Contains(t, out, "name: online-store-prod")
	assert.Contains(t, out, "projectName: online-store")
	assert.Contains(t, out, "environment: dev")

	// projectRelease is deliberately unset; the controller seeds it.
	assert.NotContains(t, out, "projectRelease:")
}

func TestGenerate_BindingsNote(t *testing.T) {
	opts := baseOpts()
	opts.BindingsNote = "No ProjectReleaseBindings were generated: deployment pipeline \"default\" defines no environments."

	g := NewGenerator(schemaFrom(t, testSchema), opts)
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Equal(t, 1, countDocs(t, out))
	assert.Contains(t, out, "# No ProjectReleaseBindings were generated")
	assert.Contains(t, out, "# Generated by occ project scaffold")
}

func TestGenerate_BindingsNote_SurvivesSkipComments(t *testing.T) {
	opts := baseOpts()
	opts.IncludeFieldDescriptions = false
	opts.IncludeStructuralComments = false
	opts.BindingsNote = "pipeline has no environments"

	g := NewGenerator(schemaFrom(t, testSchema), opts)
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Equal(t, 1, countDocs(t, out))
	assert.Contains(t, out, "# pipeline has no environments")
	assert.NotContains(t, out, "Generated by occ project scaffold")
}

func TestGenerate_ClusterProjectTypeKind(t *testing.T) {
	opts := baseOpts()
	opts.ProjectTypeKind = "ClusterProjectType"
	opts.ProjectTypeName = "default"

	g := NewGenerator(schemaFrom(t, testSchema), opts)
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Contains(t, out, "kind: ClusterProjectType")
	assert.Contains(t, out, "name: default")
}

func TestGenerate_NilSchema_OmitsParameters(t *testing.T) {
	g := NewGenerator(nil, baseOpts())
	out, err := g.Generate()
	require.NoError(t, err)

	assert.Equal(t, 1, countDocs(t, out))
	assert.Contains(t, out, "kind: Project")
	assert.NotContains(t, out, "parameters:")
}

func TestGenerate_EmptyPropertiesSchema_OmitsParameters(t *testing.T) {
	g := NewGenerator(schemaFrom(t, `{"type":"object"}`), baseOpts())
	out, err := g.Generate()
	require.NoError(t, err)

	assert.NotContains(t, out, "parameters:")
}

func TestNewGenerator_NilOptions(t *testing.T) {
	g := NewGenerator(nil, nil)
	require.NotNil(t, g)
	_, err := g.Generate()
	require.NoError(t, err)
}
