// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateProjectType provides a mock function with given fields: ctx, namespaceName, pt
func (_m *MockService) CreateProjectType(ctx context.Context, namespaceName string, pt *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error) {
	ret := _m.Called(ctx, namespaceName, pt)

	if len(ret) == 0 {
		panic("no return value specified for CreateProjectType")
	}

	var r0 *v1alpha1.ProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error)); ok {
		return rf(ctx, namespaceName, pt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectType) *v1alpha1.ProjectType); ok {
		r0 = rf(ctx, namespaceName, pt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProjectType) error); ok {
		r1 = rf(ctx, namespaceName, pt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProjectType'
type MockService_CreateProjectType_Call struct {
	*mock.Call
}

// CreateProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - pt *v1alpha1.ProjectType
func (_e *MockService_Expecter) CreateProjectType(ctx interface{}, namespaceName interface{}, pt interface{}) *MockService_CreateProjectType_Call {
	return &MockService_CreateProjectType_Call{Call: _e.mock.On("CreateProjectType", ctx, namespaceName, pt)}
}

func (_c *MockService_CreateProjectType_Call) Run(run func(ctx context.Context, namespaceName string, pt *v1alpha1.ProjectType)) *MockService_CreateProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ProjectType))
	})
	return _c
}

func (_c *MockService_CreateProjectType_Call) Return(_a0 *v1alpha1.ProjectType, _a1 error) *MockService_CreateProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateProjectType_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error)) *MockService_CreateProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProjectType provides a mock function with given fields: ctx, namespaceName, ptName
func (_m *MockService) DeleteProjectType(ctx context.Context, namespaceName string, ptName string) error {
	ret := _m.Called(ctx, namespaceName, ptName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProjectType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, ptName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProjectType'
type MockService_DeleteProjectType_Call struct {
	*mock.Call
}

// DeleteProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ptName string
func (_e *MockService_Expecter) DeleteProjectType(ctx interface{}, namespaceName interface{}, ptName interface{}) *MockService_DeleteProjectType_Call {
	return &MockService_DeleteProjectType_Call{Call: _e.mock.On("DeleteProjectType", ctx, namespaceName, ptName)}
}

func (_c *MockService_DeleteProjectType_Call) Run(run func(ctx context.Context, namespaceName string, ptName string)) *MockService_DeleteProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteProjectType_Call) Return(_a0 error) *MockService_DeleteProjectType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteProjectType_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectType provides a mock function with given fields: ctx, namespaceName, ptName
func (_m *MockService) GetProjectType(ctx context.Context, namespaceName string, ptName string) (*v1alpha1.ProjectType, error) {
	ret := _m.Called(ctx, namespaceName, ptName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectType")
	}

	var r0 *v1alpha1.ProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ProjectType, error)); ok {
		return rf(ctx, namespaceName, ptName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ProjectType); ok {
		r0 = rf(ctx, namespaceName, ptName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, ptName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectType'
type MockService_GetProjectType_Call struct {
	*mock.Call
}

// GetProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ptName string
func (_e *MockService_Expecter) GetProjectType(ctx interface{}, namespaceName interface{}, ptName interface{}) *MockService_GetProjectType_Call {
	return &MockService_GetProjectType_Call{Call: _e.mock.On("GetProjectType", ctx, namespaceName, ptName)}
}

func (_c *MockService_GetProjectType_Call) Run(run func(ctx context.Context, namespaceName string, ptName string)) *MockService_GetProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetProjectType_Call) Return(_a0 *v1alpha1.ProjectType, _a1 error) *MockService_GetProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProjectType_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ProjectType, error)) *MockService_GetProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectTypeSchema provides a mock function with given fields: ctx, namespaceName, ptName
func (_m *MockService) GetProjectTypeSchema(ctx context.Context, namespaceName string, ptName string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, namespaceName, ptName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectTypeSchema")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, error)); ok {
		return rf(ctx, namespaceName, ptName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = rf(ctx, namespaceName, ptName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, ptName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProjectTypeSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectTypeSchema'
type MockService_GetProjectTypeSchema_Call struct {
	*mock.Call
}

// GetProjectTypeSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ptName string
func (_e *MockService_Expecter) GetProjectTypeSchema(ctx interface{}, namespaceName interface{}, ptName interface{}) *MockService_GetProjectTypeSchema_Call {
	return &MockService_GetProjectTypeSchema_Call{Call: _e.mock.On("GetProjectTypeSchema", ctx, namespaceName, ptName)}
}

func (_c *MockService_GetProjectTypeSchema_Call) Run(run func(ctx context.Context, namespaceName string, ptName string)) *MockService_GetProjectTypeSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetProjectTypeSchema_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetProjectTypeSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProjectTypeSchema_Call) RunAndReturn(run func(context.Context, string, string) (map[string]interface{}, error)) *MockService_GetProjectTypeSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectTypes provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListProjectTypes(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ProjectType], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectTypes")
	}

	var r0 *services.ListResult[v1alpha1.ProjectType]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectType], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.ProjectType]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ProjectType])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListProjectTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectTypes'
type MockService_ListProjectTypes_Call struct {
	*mock.Call
}

// ListProjectTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListProjectTypes(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListProjectTypes_Call {
	return &MockService_ListProjectTypes_Call{Call: _e.mock.On("ListProjectTypes", ctx, namespaceName, opts)}
}

func (_c *MockService_ListProjectTypes_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListProjectTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListProjectTypes_Call) Return(_a0 *services.ListResult[v1alpha1.ProjectType], _a1 error) *MockService_ListProjectTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListProjectTypes_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ProjectType], error)) *MockService_ListProjectTypes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProjectType provides a mock function with given fields: ctx, namespaceName, pt
func (_m *MockService) UpdateProjectType(ctx context.Context, namespaceName string, pt *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error) {
	ret := _m.Called(ctx, namespaceName, pt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProjectType")
	}

	var r0 *v1alpha1.ProjectType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error)); ok {
		return rf(ctx, namespaceName, pt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProjectType) *v1alpha1.ProjectType); ok {
		r0 = rf(ctx, namespaceName, pt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ProjectType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProjectType) error); ok {
		r1 = rf(ctx, namespaceName, pt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateProjectType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProjectType'
type MockService_UpdateProjectType_Call struct {
	*mock.Call
}

// UpdateProjectType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - pt *v1alpha1.ProjectType
func (_e *MockService_Expecter) UpdateProjectType(ctx interface{}, namespaceName interface{}, pt interface{}) *MockService_UpdateProjectType_Call {
	return &MockService_UpdateProjectType_Call{Call: _e.mock.On("UpdateProjectType", ctx, namespaceName, pt)}
}

func (_c *MockService_UpdateProjectType_Call) Run(run func(ctx context.Context, namespaceName string, pt *v1alpha1.ProjectType)) *MockService_UpdateProjectType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ProjectType))
	})
	return _c
}

func (_c *MockService_UpdateProjectType_Call) Return(_a0 *v1alpha1.ProjectType, _a1 error) *MockService_UpdateProjectType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateProjectType_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ProjectType) (*v1alpha1.ProjectType, error)) *MockService_UpdateProjectType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
