{{- if and .Values.gateway.enabled (eq (.Values.gateway.gatewayClassName | default "kgateway") "kgateway") }}
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: enable-websocket
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-default
  upgradeConfig:
    enabledUpgrades:
      - websocket
{{- end }}
