// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by tools/auditgen. DO NOT EDIT.

package audit

import (
	"github.com/openchoreo/openchoreo/internal/server/middleware/audit"
)

// generatedOperationDefs returns one audit.OperationDef per state-modifying
// REST operation in the OpenAPI spec, minus the operations in
// excludedOperationIDs.
//
// Regenerate with: make code.gen (runs tools/auditgen).
func generatedOperationDefs() []audit.OperationDef {
	return []audit.OperationDef{
		{
			ID: "QueryAuditLogs", Action: "read_audit_log", ResourceType: "auditlog",
			Category: audit.CategoryAccess,
		},
		{
			ID: "UpdateIncident", Action: "update_incident", ResourceType: "incident",
			Category: audit.CategoryManagement, RESTResourceParam: "incidentId",
		},
	}
}
