// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

// Package trait handles trait processing for component rendering.
//
// Traits can create new resources and patch existing resources generated by
// the ComponentType.
package trait

import (
	"context"
	"encoding/json"
	"fmt"
	"maps"
	"strings"

	"github.com/openchoreo/openchoreo/api/v1alpha1"
	"github.com/openchoreo/openchoreo/internal/patch"
	"github.com/openchoreo/openchoreo/internal/pipeline/component/renderer"
	"github.com/openchoreo/openchoreo/internal/template"
)

// maxPatchOperations bounds the total number of rendered JSON Patch operations applied
// across all target resources in one component render.
//
// forEach multiplies on both sides of a patch: a ComponentType can expand to hundreds of
// resources, and a trait patch with its own forEach applies once per item to every matching
// target, so items x targets grows as a product. That product is JSON-Patch work, not CEL
// evaluation, so neither the per-expression cost limit nor the reconcile cost budget can see
// it - each iteration renders the same cheap operations and then does unmetered work
// proportional to the size of the resource it patches.
//
// The bound is per render because the counter lives on the Processor, which the component
// pipeline builds fresh for each RenderComponent call, so every trait on a component draws
// from the same allowance. Real samples measure in the tens of operations; 10,000 leaves
// two orders of magnitude of headroom while capping the cross product well below the
// million-application shape a hostile pair of forEach expressions can otherwise reach.
const maxPatchOperations uint64 = 10_000

// Processor handles trait creates and patches.
//
// A Processor is scoped to one component render: the pipeline constructs one per
// RenderComponent call, which is what makes patchOperations a per-render count.
// It is not safe for concurrent use.
type Processor struct {
	templateEngine *template.Engine

	patchOperations uint64
}

// TargetSpec describes how to locate a resource when applying patches.
type TargetSpec struct {
	Kind        string
	Group       string
	Version     string
	Where       string
	TargetPlane string
}

// NewProcessor creates a new trait processor.
func NewProcessor(templateEngine *template.Engine) *Processor {
	return &Processor{
		templateEngine: templateEngine,
	}
}

// ProcessTraits applies all traits to the base resources.
//
// For each trait, in order:
//   - Apply creates (new resources with targetPlane)
//   - Apply patches (modify existing resources, respecting targetPlane)
//   - Apply removes (delete entire resources, respecting targetPlane)
//
// Removes runs last so a single trait can fully express a substitution: create a
// replacement, optionally patch siblings, then drop the unwanted base resource.
func (p *Processor) ProcessTraits(
	ctx context.Context,
	resources []renderer.RenderedResource,
	trait *v1alpha1.Trait,
	traitContext map[string]any,
) ([]renderer.RenderedResource, error) {
	// Apply creates first
	var err error
	resources, err = p.ApplyTraitCreates(ctx, resources, trait, traitContext)
	if err != nil {
		return nil, err
	}

	// Then apply patches
	err = p.ApplyTraitPatches(ctx, resources, trait, traitContext)
	if err != nil {
		return nil, err
	}

	// Finally apply removes
	resources, err = p.ApplyTraitRemoves(ctx, resources, trait, traitContext)
	if err != nil {
		return nil, err
	}

	return resources, nil
}

// ApplyTraitCreates renders and adds new resources from trait.spec.creates with targetPlane metadata.
// Supports includeWhen for conditional creation and forEach for generating multiple resources.
func (p *Processor) ApplyTraitCreates(
	ctx context.Context,
	resources []renderer.RenderedResource,
	trait *v1alpha1.Trait,
	traitContext map[string]any,
) ([]renderer.RenderedResource, error) {
	for i, createTemplate := range trait.Spec.Creates {
		createPath := fmt.Sprintf("trait %s create #%d", trait.Name, i)

		// Check includeWhen condition using shared helper
		include, err := renderer.ShouldInclude(ctx, p.templateEngine, createTemplate.IncludeWhen, traitContext)
		if err != nil {
			return nil, fmt.Errorf("failed to evaluate includeWhen for %s: %w", createPath, err)
		}
		if !include {
			continue
		}

		// Handle forEach or single render
		if createTemplate.ForEach != "" {
			itemContexts, err := renderer.EvalForEach(ctx, p.templateEngine, createTemplate.ForEach, createTemplate.Var, traitContext)
			if err != nil {
				return nil, fmt.Errorf("failed to evaluate forEach for %s: %w", createPath, err)
			}
			for _, itemContext := range itemContexts {
				rendered, err := p.renderSingleCreate(ctx, createTemplate, itemContext, createPath)
				if err != nil {
					return nil, err
				}
				resources = append(resources, rendered)
			}
		} else {
			rendered, err := p.renderSingleCreate(ctx, createTemplate, traitContext, createPath)
			if err != nil {
				return nil, err
			}
			resources = append(resources, rendered)
		}
	}

	return resources, nil
}

// renderSingleCreate renders a single TraitCreate template and returns a RenderedResource.
func (p *Processor) renderSingleCreate(
	ctx context.Context,
	create v1alpha1.TraitCreate,
	celContext map[string]any,
	path string,
) (renderer.RenderedResource, error) {
	var templateData any
	if err := json.Unmarshal(create.Template.Raw, &templateData); err != nil {
		return renderer.RenderedResource{}, fmt.Errorf("failed to unmarshal create template for %s: %w", path, err)
	}

	rendered, err := p.templateEngine.Render(ctx, templateData, celContext)
	if err != nil {
		return renderer.RenderedResource{}, fmt.Errorf("failed to render create template for %s: %w", path, err)
	}

	resourceMap, ok := rendered.(map[string]any)
	if !ok {
		return renderer.RenderedResource{}, fmt.Errorf("create template must render to object for %s, got %T", path, rendered)
	}

	cleanedAny := template.RemoveOmittedFields(resourceMap)
	cleaned, ok := cleanedAny.(map[string]any)
	if !ok {
		return renderer.RenderedResource{}, fmt.Errorf("RemoveOmittedFields returned unexpected type %T for %s", cleanedAny, path)
	}

	return renderer.RenderedResource{
		Resource:    cleaned,
		TargetPlane: create.TargetPlane,
	}, nil
}

// ApplyTraitPatches applies trait patches to existing resources.
//
// This function handles the orchestration of:
//   - forEach iteration over collections (arrays and maps)
//   - Resource targeting (finding which resources to patch, respecting targetPlane)
//   - CEL rendering of patch operations and where clauses
//   - Delegating to patch.ApplyPatches for the actual patching
//
// For forEach with maps, keys are iterated in sorted order with each item having
// .key and .value fields.
//
// The patch package itself only handles the low-level mechanics of applying
// operations to a single resource.
func (p *Processor) ApplyTraitPatches(
	ctx context.Context,
	resources []renderer.RenderedResource,
	trait *v1alpha1.Trait,
	traitContext map[string]any,
) error {
	for i, traitPatch := range trait.Spec.Patches {
		if err := p.applyPatch(ctx, resources, trait.Name, i, traitPatch, traitContext); err != nil {
			return fmt.Errorf("failed to apply trait patch #%d for trait %s: %w", i, trait.Name, err)
		}
	}

	return nil
}

// applyPatch applies a single patch specification to resources.
// Handles forEach iteration, targeting, filtering, targetPlane matching, and CEL rendering.
func (p *Processor) applyPatch(
	ctx context.Context,
	resources []renderer.RenderedResource,
	traitName string,
	patchIndex int,
	traitPatch v1alpha1.TraitPatch,
	baseContext map[string]any,
) error {
	// Handle forEach iteration if specified
	if traitPatch.ForEach != "" {
		return p.applyPatchWithForEach(ctx, resources, traitName, patchIndex, traitPatch, baseContext)
	}

	// No forEach - apply once with base context
	return p.applyPatchOnce(ctx, resources, traitName, patchIndex, traitPatch, baseContext)
}

// applyPatchWithForEach handles forEach iteration for a patch.
// Supports both arrays and maps. For maps, items are {key, value} entries sorted by key.
func (p *Processor) applyPatchWithForEach(
	ctx context.Context,
	resources []renderer.RenderedResource,
	traitName string,
	patchIndex int,
	traitPatch v1alpha1.TraitPatch,
	baseContext map[string]any,
) error {
	// Evaluate the forEach expression to get the list of items
	itemsRaw, err := p.templateEngine.Render(ctx, traitPatch.ForEach, baseContext)
	if err != nil {
		return fmt.Errorf("failed to evaluate forEach expression '%s' for trait %s patch #%d: %w", template.TruncateFragment(traitPatch.ForEach), traitName, patchIndex, err)
	}

	// Convert result to iterable items (supports arrays and maps)
	items, err := renderer.ToIterableItems(ctx, itemsRaw)
	if err != nil {
		return fmt.Errorf("invalid forEach result for trait %s patch #%d: %w", traitName, patchIndex, err)
	}

	// Determine the variable name for each iteration (defaults to "item")
	varName := traitPatch.Var
	if varName == "" {
		varName = "item"
	}

	// Iterate through each item
	for i, item := range items {
		// Shallow clone context for this iteration to avoid cross-iteration contamination.
		// A shallow copy is sufficient because:
		//   - We only add one new key (the loop variable)
		//   - The template engine doesn't mutate map values (only reads them)
		//   - We need isolation so one iteration's loop variable doesn't affect another
		iterContext := maps.Clone(baseContext)
		iterContext[varName] = item

		// Apply patch operations with this iteration's context
		if err := p.applyPatchOnce(ctx, resources, traitName, patchIndex, traitPatch, iterContext); err != nil {
			return fmt.Errorf("forEach iteration %d failed: %w", i, err)
		}
	}

	return nil
}

// applyPatchOnce applies a patch to all matching targets with a given context.
// Respects targetPlane - only patches resources in the same plane.
func (p *Processor) applyPatchOnce(
	ctx context.Context,
	resources []renderer.RenderedResource,
	traitName string,
	patchIndex int,
	traitPatch v1alpha1.TraitPatch,
	celContext map[string]any,
) error {
	// Find target resources based on targetPlane and Kind/Group/Version
	target := TargetSpec{
		Kind:        traitPatch.Target.Kind,
		Group:       traitPatch.Target.Group,
		Version:     traitPatch.Target.Version,
		Where:       traitPatch.Target.Where,
		TargetPlane: traitPatch.TargetPlane,
	}
	matchedResources := FindTargetResources(resources, target)

	if len(matchedResources) == 0 {
		// No matching resources - this is okay, patch is a no-op
		return nil
	}

	// Filter targets using where clause if specified
	var targets []renderer.RenderedResource
	if target.Where != "" {
		filtered, err := p.filterTargets(ctx, matchedResources, target.Where, celContext, traitName, patchIndex)
		if err != nil {
			return err
		}
		targets = filtered
	} else {
		targets = matchedResources
	}

	// Render patch operations with CEL
	renderedOps, err := p.renderOperations(ctx, traitPatch.Operations, celContext, traitName, patchIndex)
	if err != nil {
		return err
	}

	// Every patch application in this render funnels through the loop below. Charge each
	// operation for every target before applying the batch.
	if err := p.chargePatchOperations(uint64(len(targets)), uint64(len(renderedOps))); err != nil {
		return fmt.Errorf("trait %s patch #%d: %w", traitName, patchIndex, err)
	}

	// Apply rendered operations to each target using the simple patch function
	// Note: patches modify the Resource field in-place
	for _, rr := range targets {
		// Applying a patch performs no CEL evaluation, so the engine's own cancellation
		// checks never run here. The whole batch was charged up front, and without this
		// check the remaining applications would run to completion after the render
		// deadline has already expired.
		if err := ctx.Err(); err != nil {
			return fmt.Errorf("trait %s patch #%d interrupted: %w", traitName, patchIndex, err)
		}
		if err := patch.ApplyPatches(rr.Resource, renderedOps); err != nil {
			// Extract resource identity for better error message
			kind, _ := rr.Resource["kind"].(string)
			metadata, _ := rr.Resource["metadata"].(map[string]any)
			name, _ := metadata["name"].(string)
			resourceID := fmt.Sprintf("%s/%s", template.TruncateFragment(kind), template.TruncateFragment(name))
			if resourceID == "/" {
				resourceID = "unknown resource"
			}
			return fmt.Errorf("failed to apply patches to %s for trait %s patch #%d: %w", resourceID, traitName, patchIndex, err)
		}
	}

	return nil
}

// chargePatchOperations adds targets x operations to this render's running total.
//
// The error wraps template.ErrExpansionLimitExceeded because the count depends only on the
// component's own shape - how many resources it renders and how many items its trait
// patches iterate - so an unchanged object produces the same count on every reconcile.
// The message names the total the batch would have reached and the cap; both are deterministic for
// fixed inputs, so it is stable enough to sit in a status condition, and the total is what
// tells an operator whether they are marginally or wildly over.
func (p *Processor) chargePatchOperations(targets, operations uint64) error {
	if targets == 0 || operations == 0 {
		return nil
	}

	// Divide rather than multiply: targets x operations is compared against what is left,
	// so the check itself cannot overflow the counter it is protecting.
	remaining := maxPatchOperations - p.patchOperations
	if targets > remaining/operations {
		return fmt.Errorf("%w: trait patches would apply %d operations in one render, exceeding the limit of %d",
			template.ErrExpansionLimitExceeded, p.patchOperations+targets*operations, maxPatchOperations)
	}
	p.patchOperations += targets * operations
	return nil
}

// filterTargets filters resources based on a where clause.
// The where clause is evaluated as a CEL expression with "resource" bound to each target's Resource field.
func (p *Processor) filterTargets(
	ctx context.Context,
	targets []renderer.RenderedResource,
	whereClause string,
	baseContext map[string]any,
	traitName string,
	patchIndex int,
) ([]renderer.RenderedResource, error) {
	filtered := make([]renderer.RenderedResource, 0, len(targets))

	// Save previous "resource" binding if it exists
	previous, had := baseContext["resource"]

	for _, rr := range targets {
		// Bind the current resource for evaluation
		baseContext["resource"] = rr.Resource

		// Evaluate the where clause
		result, err := p.templateEngine.Render(ctx, whereClause, baseContext)
		if err != nil {
			// Restore previous binding before returning error
			if had {
				baseContext["resource"] = previous
			} else {
				delete(baseContext, "resource")
			}
			return nil, fmt.Errorf("failed to evaluate where clause '%s' for trait %s patch #%d: %w", template.TruncateFragment(whereClause), traitName, patchIndex, err)
		}

		// Check if result is boolean true
		boolResult, ok := result.(bool)
		if !ok {
			// Restore previous binding before returning error
			if had {
				baseContext["resource"] = previous
			} else {
				delete(baseContext, "resource")
			}
			return nil, fmt.Errorf("where clause '%s' must evaluate to boolean for trait %s patch #%d, got %T", template.TruncateFragment(whereClause), traitName, patchIndex, result)
		}

		if boolResult {
			filtered = append(filtered, rr)
		}
	}

	// Restore previous "resource" binding
	if had {
		baseContext["resource"] = previous
	} else {
		delete(baseContext, "resource")
	}

	return filtered, nil
}

// renderOperations renders all patch operations using CEL.
// Both the path and value of each operation may contain ${...} expressions.
func (p *Processor) renderOperations(
	ctx context.Context,
	operations []v1alpha1.JSONPatchOperation,
	celContext map[string]any,
	traitName string,
	patchIndex int,
) ([]patch.JSONPatchOperation, error) {
	rendered := make([]patch.JSONPatchOperation, len(operations))

	for i, op := range operations {
		// Render the path (which may contain CEL expressions)
		pathValue, err := p.templateEngine.Render(ctx, op.Path, celContext)
		if err != nil {
			return nil, fmt.Errorf("failed to render path '%s' for trait %s patch #%d operation #%d: %w", op.Path, traitName, patchIndex, i, err)
		}

		pathStr, ok := pathValue.(string)
		if !ok {
			return nil, fmt.Errorf("path '%s' must evaluate to string for trait %s patch #%d operation #%d, got %T", op.Path, traitName, patchIndex, i, pathValue)
		}

		// Render the value (unless this is a remove operation)
		var value any
		if op.Op != "remove" {
			// Extract value from RawExtension
			if op.Value != nil && op.Value.Raw != nil {
				if err := json.Unmarshal(op.Value.Raw, &value); err != nil {
					return nil, fmt.Errorf("failed to unmarshal value for trait %s patch #%d operation #%d: %w", traitName, patchIndex, i, err)
				}

				// Render the value (which may contain CEL expressions)
				value, err = p.templateEngine.Render(ctx, value, celContext)
				if err != nil {
					return nil, fmt.Errorf("failed to render value for trait %s patch #%d operation #%d: %w", traitName, patchIndex, i, err)
				}
			}
		}

		rendered[i] = patch.JSONPatchOperation{
			Op:    op.Op,
			Path:  pathStr,
			Value: value,
		}
	}

	return rendered, nil
}

// FindTargetResources filters resources based on TargetPlane, Kind, Group, and Version.
//
// Matching rules:
//   - If target.TargetPlane is set, resource.TargetPlane must match
//   - If target.Kind is set, resource.kind must match
//   - If target.Group is set, the group portion of resource.apiVersion must match
//   - If target.Version is set, the version portion of resource.apiVersion must match
//
// An empty field in the target spec means "match any value".
//
// apiVersion is split into group/version:
//   - "apps/v1" → group="apps", version="v1"
//   - "v1" → group="", version="v1" (core API)
//
// Note: Additional filtering (e.g., by name or custom where clauses) should be
// done by the caller after calling this function.
func FindTargetResources(resources []renderer.RenderedResource, target TargetSpec) []renderer.RenderedResource {
	matches := make([]renderer.RenderedResource, 0, len(resources))
	for _, rr := range resources {
		// Match TargetPlane
		if target.TargetPlane != "" && rr.TargetPlane != target.TargetPlane {
			continue
		}

		resource := rr.Resource

		// Match Kind
		if target.Kind != "" {
			if kind, ok := resource["kind"].(string); !ok || kind != target.Kind {
				continue
			}
		}

		// Match Group and Version (extracted from apiVersion)
		group := ""
		version := ""
		if gv, ok := resource["apiVersion"].(string); ok {
			group, version = splitAPIVersion(gv)
		}
		if target.Group != "" && group != target.Group {
			continue
		}
		if target.Version != "" && version != target.Version {
			continue
		}

		matches = append(matches, rr)
	}
	return matches
}

// ApplyTraitRemoves deletes resources matched by trait.spec.removes.
//
// For each remove entry, resources matching TargetPlane/Kind/Group/Version are
// found, optionally filtered by a `where` CEL expression, and the matched
// resources are removed entirely from the slice. Supports forEach iteration.
//
// Returns the (possibly shorter) resource slice with matched resources excluded.
func (p *Processor) ApplyTraitRemoves(
	ctx context.Context,
	resources []renderer.RenderedResource,
	trait *v1alpha1.Trait,
	traitContext map[string]any,
) ([]renderer.RenderedResource, error) {
	if len(trait.Spec.Removes) == 0 {
		return resources, nil
	}

	// Use pointer-identity to mark resources for deletion. The slice may grow during
	// processing only for creates/patches (already done), so addresses are stable here.
	toRemove := make(map[*renderer.RenderedResource]struct{})

	for i := range trait.Spec.Removes {
		remove := trait.Spec.Removes[i]
		if err := p.collectRemovalsForEntry(ctx, resources, trait.Name, i, remove, traitContext, toRemove); err != nil {
			return nil, fmt.Errorf("failed to apply trait remove #%d for trait %s: %w", i, trait.Name, err)
		}
	}

	if len(toRemove) == 0 {
		return resources, nil
	}

	filtered := make([]renderer.RenderedResource, 0, len(resources)-len(toRemove))
	for i := range resources {
		if _, drop := toRemove[&resources[i]]; drop {
			continue
		}
		filtered = append(filtered, resources[i])
	}
	return filtered, nil
}

// collectRemovalsForEntry evaluates one TraitRemove entry (handling forEach) and
// records every matching resource into toRemove. Resources are tracked by their
// address in the original slice so the caller can do one pass to rebuild.
func (p *Processor) collectRemovalsForEntry(
	ctx context.Context,
	resources []renderer.RenderedResource,
	traitName string,
	removeIndex int,
	remove v1alpha1.TraitRemove,
	baseContext map[string]any,
	toRemove map[*renderer.RenderedResource]struct{},
) error {
	if remove.ForEach == "" {
		return p.collectRemovalsOnce(ctx, resources, traitName, removeIndex, remove, baseContext, toRemove)
	}

	itemsRaw, err := p.templateEngine.Render(ctx, remove.ForEach, baseContext)
	if err != nil {
		return fmt.Errorf("failed to evaluate forEach expression '%s' for trait %s remove #%d: %w", template.TruncateFragment(remove.ForEach), traitName, removeIndex, err)
	}

	items, err := renderer.ToIterableItems(ctx, itemsRaw)
	if err != nil {
		return fmt.Errorf("invalid forEach result for trait %s remove #%d: %w", traitName, removeIndex, err)
	}

	varName := remove.Var
	if varName == "" {
		varName = "item"
	}

	for i, item := range items {
		iterContext := maps.Clone(baseContext)
		iterContext[varName] = item

		if err := p.collectRemovalsOnce(ctx, resources, traitName, removeIndex, remove, iterContext, toRemove); err != nil {
			return fmt.Errorf("forEach iteration %d failed: %w", i, err)
		}
	}

	return nil
}

// collectRemovalsOnce finds resources matching the remove's target+where and
// records them by pointer in toRemove.
func (p *Processor) collectRemovalsOnce(
	ctx context.Context,
	resources []renderer.RenderedResource,
	traitName string,
	removeIndex int,
	remove v1alpha1.TraitRemove,
	celContext map[string]any,
	toRemove map[*renderer.RenderedResource]struct{},
) error {
	target := TargetSpec{
		Kind:        remove.Target.Kind,
		Group:       remove.Target.Group,
		Version:     remove.Target.Version,
		Where:       remove.Target.Where,
		TargetPlane: remove.TargetPlane,
	}

	// Walk resources by index so we can record stable pointers into the original slice.
	previous, had := celContext["resource"]
	defer func() {
		if had {
			celContext["resource"] = previous
		} else {
			delete(celContext, "resource")
		}
	}()

	for i := range resources {
		rr := &resources[i]
		if !matchesTarget(*rr, target) {
			continue
		}

		if target.Where != "" {
			celContext["resource"] = rr.Resource
			result, err := p.templateEngine.Render(ctx, target.Where, celContext)
			if err != nil {
				return fmt.Errorf("failed to evaluate where clause '%s' for trait %s remove #%d: %w", template.TruncateFragment(target.Where), traitName, removeIndex, err)
			}
			boolResult, ok := result.(bool)
			if !ok {
				return fmt.Errorf("where clause '%s' must evaluate to boolean for trait %s remove #%d, got %T", template.TruncateFragment(target.Where), traitName, removeIndex, result)
			}
			if !boolResult {
				continue
			}
		}

		toRemove[rr] = struct{}{}
	}

	return nil
}

// matchesTarget reports whether rr matches the given TargetSpec on plane, kind,
// group and version. The `where` clause is evaluated separately by the caller.
//
// This mirrors FindTargetResources, but operates on a single resource so callers
// can keep stable pointer identity while iterating.
func matchesTarget(rr renderer.RenderedResource, target TargetSpec) bool {
	if target.TargetPlane != "" && rr.TargetPlane != target.TargetPlane {
		return false
	}

	resource := rr.Resource

	if target.Kind != "" {
		kind, ok := resource["kind"].(string)
		if !ok || kind != target.Kind {
			return false
		}
	}

	group := ""
	version := ""
	if gv, ok := resource["apiVersion"].(string); ok {
		group, version = splitAPIVersion(gv)
	}
	if target.Group != "" && group != target.Group {
		return false
	}
	if target.Version != "" && version != target.Version {
		return false
	}

	return true
}

// splitAPIVersion separates a Kubernetes apiVersion into group and version parts.
//
// Examples:
//   - "apps/v1" → ("apps", "v1")
//   - "v1" → ("", "v1")         // Core API group
//   - "" → ("", "")
func splitAPIVersion(apiVersion string) (group, version string) {
	if apiVersion == "" {
		return "", ""
	}
	if strings.Contains(apiVersion, "/") {
		parts := strings.SplitN(apiVersion, "/", 2)
		return parts[0], parts[1]
	}
	// No slash means it's a core API (e.g., "v1")
	return "", apiVersion
}
